### ISSUE TITLE
missing player instances / changed player instances (spigot 1.8.8)

### ISSUE THREAD

**Issue by Blamo27** [NoCheatPlus/Issues#129]
> Spigot version : 1.8.8

There are some players that appear on the list but are not connected to the server.
(Ghost players)

NoCheatPlus error: 
> [18:16:25 WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (22 instead of 25) | changed player instances (3)

(We are using CombatTagPlus)

Can you help me ? Thank you.

**Comment by asofold** [comment]
This is odd, because NCP shouldn't store player instances past 1.7.10. Is that PaperSpigot or default Spigot? Best would be, if you just post the full output of the 'ncp version' command with every new issue, it'll help identifying some odds and ends quickly.

**Comment by Blamo27** [comment]
http://i.imgur.com/5yTP6c5.png

**Comment by asofold** [comment]
Does 'Player instances are stored for efficiency.' show up in the startup log? Would be both in ncp and server log files.

**Comment by Blamo27** [comment]
[05:30:17] [Server thread/INFO]: [INFO][NoCheatPlus] Sat Mar 19 05:30:17 CET 2016
[05:30:17] [Server thread/INFO]: Player instances are stored for efficiency.

**Comment by asofold** [comment]
Ok thank you, that is a bug clearly. That player instance storing is for legacy server versions only.

**Comment by Blamo27** [comment]
Can you explain what you mean ?

**Comment by asofold** [comment]
The log line '[05:30:17] [Server thread/INFO]: Player instances are stored for efficiency.' means that a feature is activated that isn't supposed to be activated, thus it's probably a bug.

Are you sure you don't have any duplicate NoCheatPlus jars in the plugins or server directory, including accidental renames?

**Comment by Blamo27** [comment]
I'm sure, no duplicate NoCheatPlus

**Comment by Blamo27** [comment]
>> Which feature ?

**Comment by asofold** [comment]
It's not really visible, except with the warning. On old CraftBukkit versions, before spigot 1.7.10, player lookup by name has been inefficient, so NCP stored the objects internally. However that should be auto-disabled on spigot since 1.7.10.

Will be fixed with the next build.

**Comment by Blamo27** [comment]
So, is this bug causing the apparition of players not connected on the list ?

**Comment by asofold** [comment]
I don't think players have been removed or couldn't connect to the server.

Combat logging plugins often add fake players to counter combat logging, but other plugins might not notice the difference between fake players and real players. Since NoCheatPlus kept track of players found in events like damage from attacks, and cross checked vs. the 'official' online player list that the server reports, it would see a difference due to the faked players.

The bug has been that NCP kept track of players at all, because it's just not needed past spigot 1.7.10 anymore. This shouldn't be a concern anymore since build 952.

**Comment by Blamo27** [comment]
Okey thanks you

**Comment by Blamo27** [comment]
Not fixed yet, with the last build (925)
> [18:42:03 WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (16 instead of 17)

**Comment by asofold** [comment]
925 is by far not the latest build. The fix is on the Jenkins server, it's about build 954 now.

**Comment by Blamo27** [comment]
So build fixed on 955 ?
If that's the case, this is not fixed.

**Comment by Blamo27** [comment]
>[19:05:12 WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (15 instead of 17)

**Comment by asofold** [comment]
Does it still show "Player instances are stored for efficiency." in the server log? That part should be gone, all would be fine if that one was gone .

The missing online players message might still show, because NCP still might cross-check the numbers found during checking vs. the player list. You can suppress these warnings ion the configuration (data.consistencychecks.suppresswarnings) for the time being.

**Comment by Blamo27** [comment]
The "Player instances are stored for efficiency." error is gone, but the error "[NoCheatPlus] DataMan inconsistencies: missing online players (1) | wrong number of online players (15 instead of 17)" still appears in the logs, which is the main issue for us : because of this, we still have the "ghost player" bug that happens to random players (we don't know why), which prevent them from reconnecting (since their account is still considered online, even though we can't kick / ban / etc this ghost account).

**Comment by asofold** [comment]
Does NCP prevent them from connecting? I would assume NCP isn't related to causing that issue, but would be interesting to know.

* What disconnect/denial messages do players receive when they try to connect, but are denied to?
* Are plugins that might be related (npc plugins, combat tag plugins...) ensured to be officially compatible with 1.8.8 (in case of updating from roughly before 1.8.3)?
* Any other error messages in the server log?

**Comment by Blamo27** [comment]
This is not NCP that is preventing.
=> Players cannot loging in, "Timed out".
The player (ghost) is already connected, and the player cannot join the server.

We've got Citizens (Quests + Sentry) and CombatTagPlus.

Error in server log: 
> handleDisconnection() called twice ghost player

**Comment by asofold** [comment]
I have that problem with a local test server at present. Instead of maximally few seconds it'll take 10-20 seconds before chunks are rendered. Then things like fly kick or just 'timed out', and 'handleDisconnection() called twice'.

Looks like lowering video settings helps slightly (chunk render distance). Someone should explain to Mojang that adjusting video settings in real time isn't such a good idea, though.

Not sure it's video settings, but looks like there is some oddities on 1.9.

**Comment by Blamo27** [comment]
So how can we fix the problem ?

**Comment by asofold** [comment]
Since you're on 1.8.x i'm not even sure it's the same issue.

I can't judge this, it could be that the hardware on client-side is just weak-ish with Minecraft rather demanding more with each update. The combat logging plugins might somehow interfere, though that would be pretty severe. Are those officially 1.8.8 compatible?

Are you using NPCs (citizens) with the same names as players or even the same UUIDs?

I don't really have a clue (plugins and server versions at latest available+compatible...?).

**Comment by Blamo27** [comment]
=> Without CombatTagPlus
> [14:51:02 WARN]: [NoCheatPlus] DataMan inconsistencies: missing online players (2) | wrong number of online players (41 instead of 44)

We don't use the same names as players with Citizens. As for the UUID, I don't think it can happen, and even if it could the problem would always occur on the same players, and it would occur every time.

And I think that we use a correct server version (there shouldn't be any compatibility issue).

We think that it is possible that this bug is caused when the client crash (his connection) or timeout.

**Comment by Blamo27** [comment]
Another thing : when the bug occurs, the ghost player can be seen physically where he was when he disconnected : we can see his "body", interract with it and even kill it (but it won't respawn afterwards). However the "body" seems to be deprived of all items. We cannot kick, ban, or remove it in any way.

**Comment by asofold** [comment]
That clearly would be something for spigot (or a plugin that somehow alters related internals). Unfortunately there won't be official updates to 1.8.8, unless i am mistaken.

There might've been a related issue on 1.9, but that likely wouldn't help us here.

Are you using a protocol-thing plugin to allow 1.9 players on?

**Comment by Blamo27** [comment]
We're not using a protocol plugin allowing players to play with 1.9 version.

**Comment by asofold** [comment]
Could be related: https://github.com/NoCheatPlus/Issues/issues/150

**Comment by Blamo27** [comment]
@asofold I removed an Instant Respawn plugins, and it's now fixed

**Comment by asofold** [comment]
Thank you very much for that information!
