### ISSUE TITLE
Passable bug

### ISSUE THREAD

**Issue by MrJoki007** [NoCheatPlus/Issues#134]
Always when a user gets Teleported on my server (with my own plugin) ncp logs a passable error

Thanks MyPictures ^^

**Comment by MyPictures** [comment]
<MrJoki007> MyPictures http://puu.sh/nP0HW.rar

Going to fill out the rest later but build in use is 954.

**Comment by asofold** [comment]
Passable is pretty normal after teleport, because the clients behave stupidly :). So they'll certainly try to move into blocks on rendering a lot of chunks, so NCP might alert.

What violation levels do they reach?

**Comment by MrJoki007** [comment]
About 500 - 600

**Comment by MyPictures** [comment]
Here the clear log.
[PassableLog-MyPictures.zip](https://github.com/NoCheatPlus/Issues/files/186759/PassableLog-MyPictures.zip)

**Comment by asofold** [comment]
This seems to be not at all unusual. Possibly you teleported to and fro a lot, and the 'ncp info ...' command would show 500-600 vl, but that vl is the sum of all violations. The actually maximally reached violation level is only shown in the violation log messages. Did you use 'ncp info PLAYER_NAME' to get 500-600?

The Minecraft client is implemented in such a way, that it'll pretend gliding/falling downwards while not having rendered/received map data, in order to 'bypass' (...) the server side fly check.

So the actual issue would be to somehow let NCP somehow detect these special moves and have the (necessary!) set-backs be silent and possibly not increasing violation levels.

So in essence this appears to be duplicating the Issue https://github.com/NoCheatPlus/Issues/issues/44 . Correct me if i'm misinterpreting things here.

**Comment by asofold** [comment]
(Closing as duplicate then, feel free to comment.)
