### ISSUE TITLE
Idea4Fix ESP

### ISSUE THREAD

**Issue by MoofMonkey** [NoCheatPlus/Issues#151]
FIX ESP: if server is vanilla and player can't see player - send fake player on:

`X = X + new Random().nextFloat()*10`
&&
`Y = Y + new Random().nextFloat()*10`
&&
`Z = Z + new Random().nextFloat()*10`

**Comment by asofold** [comment]
Two major things i'd do before:
1. If i knew a player can't see another player, why not hide that other player? Catching people going for the wrong player is nice to have, but technically it's another step on top.
2. The key point is to detect who can see whom, this would cost a bit of cpu, potentially...

**Comment by MoofMonkey** [comment]
But you can add this. May add value to the settings that enable this feature.

**Comment by MyPictures** [comment]
btw that is not a "fix" for esp its just some kind of obfuscation. Fact is: esp can not be "blocked" because it is a client sided cheat that just marks the players around you.

**Comment by asofold** [comment]
The real issue with this is the "if a player can not see another player".

If you refer to vanishing, adding players where the player would be would reveal their position, likely not what you meant or is it?

If you think we can detect who can see whom, based on terrain properties, that is probably right, however it's done at a potentially huge performance cost, because we have to calculate who can see whom (...). this task could be worth an entire plugin with an extra dedicated developer.

In fact i could imagine trying such some time, based on the code/idea of the PlayersInCubes. Currently that plugin will hide players from each other based on distance (including y-distance!), using the vanish API. One could extend this concept to check if nearby players can really see each other based on terrain properties. Before going asynchronously, one could also consider just having everybody see everybody if there are more than 5 players within a more narrow area. If the distance to see each other is too high, things get complicated though, then asynchronous processing might be needed. There can be all sorts of tricks and features built into it, like temporarily forced visibility towards another player, e.g. like a cooldown or like a penalty if players produce lots of noise or damage other players.

The vanish API isn't all too bad for such, despite not having control over the player list, but the essential point is, just to clarify, that it's somewhat complicated to do it so it doesn't take 100% CPU :p. So this will never be a quick and successful addition. Combining methods of NCP (raytracing, block checking infrastructure) and PlayersInCubes could however be a potential weekend fun project. Currently there is no fun to be expected with vehicles and lots of other stuff to do, though.

**Comment by MoofMonkey** [comment]
I think... We must reimplement minecraft server to use at least a part of GPU.
But today it's bad idea because I don't have time to do this.
So... I can start this project at summer... And start learning C++, make this project opensource & using GPU.
I think this idea will get a continuation and support

**Comment by asofold** [comment]
Per world threads already could do something, but it's another project and transforming likely is too expensive to pay off (bungeecord sort of does this already , with one server instance per world). There has been an approach but i can't recall the project name right now.

GPU ... i wouldn't specialize, and it'll stay complicated. Have a look at the [tensorflow issues](https://github.com/tensorflow/tensorflow/issues), possibly confine to opencl/amd stuff... there is and will be other optimized hardware, though admittedly GPUS are probably the cheapest multi-parallel things out there.

Concerning tasks that can be specialized, it's of course a consideration, but then again, you'll need more system and hardware specific libraries, it'll remain a two-bladed sword thing.

A part of the success of Minecraft has come due to a single developer not having to deal with all sorts of architectural and os-specific questions, other than to distribute already existent os-specific builds of libraries maintained by other people. This has been started by one developer ... 

Even implementing this in C++ would've given some performance boost, regardless multi threading, however could it have been done at all? The balance of speed of development vs. performance is another thing - and there is minetest implemented in C++ as well (...).

Concerning this issue - it probably can be done in java, possibly even on _an extra hardware box_  just like a bungee server, e.g. by examining just the packets/protocol and decide if players can see each other based on that... but it'll be somewhat complicated and most people don't intend to pay twice the price of their server (at least) to run this feature - so it's possible yes, feasible... find someone with the time/motivation.

Because you CAN
* inspect packets and build the map state (or query map state in main thread and pass to asynchronously run threads)
* do optimizations like checking if players are hidden by nearby objects/walls from sight for whichever direction, or from where their sight is blocked.
* other similar optimizations.
* do with some inaccuracies for rather far away players (meaning more simplifictions).

I've done PlayersInCubes (dbo)l, which only hides based on distance. So i would think it's possible and possibly fun to try - but you do need minimally/medium experienced people for dealing with algorithms and asynchronicity. Uh and it will be another "full time plugin job" :p
