### ISSUE TITLE
1.9 Flying by using boats

### ISSUE THREAD

**Issue by Dimatert9** [NoCheatPlus/Issues#152]
https://youtu.be/uVk-Bn1QbBY

**Comment by MyPictures** [comment]
Hi. Thank you for the info.

Do you have any more information about this? Like NC+ version, logs, name of hack client etc.

**Comment by Dimatert9** [comment]
https://yadi.sk/d/RAwAufEgqZA7A - client. Menu key is M.
This client dont work with official launcher.
Version b957

**Comment by asofold** [comment]
Horrible .... now we have to add moving checks for boats !?

**Comment by Cryptkeeper** [comment]
It actually applies to essentially every vehicle except minecarts (but I haven't tested them.)

**Comment by Dimatert9** [comment]
Check blocks under boat.
http://pastebin.com/3GMNrQTg

**Comment by asofold** [comment]
Please verify which ones have been observed :) - so far 'boats'. Horses are much different, though i don't know the internals well either.

Checking blocks under boats .... it's going to be a fully fledged moving check that way, due to the possibility of false positives for all those nasty edge cases... gravity, velocity, moving out of water sideways, ...

This is already so horrible only with boats.

**Comment by Dimatert9** [comment]
Sorry. But I do not understand what you wrote :( . My english is bad.
The cheat developer said that on a horse can fly too.

**Comment by Cryptkeeper** [comment]
@asofold Anything that is technically a "vehicle" (ridden pigs, minecarts, horses, boats) is controlled by the client as of 1.9; which allows this exploit. 

Traditionally the client sent the [Steer Vehicle](http://wiki.vg/index.php?title=Protocol&oldid=7309#Steer_Vehicle) packet which the server would acknowledge and move the player and vehicle correspondingly. This meant movement was round-trip latency dependent; which meant anything that required acknowledgement (horse movement for example) was quite glitchy.

As of 1.9, instead of sending the steering direction, the client itself informs the server of it's new location via the [Vehicle Move](http://wiki.vg/Protocol#Vehicle_Move_.28serverbound.29) packet and doesn't require a movement acknowledge from the server. 

As such the client is now authoritative over movement in 1.9.

**Comment by asofold** [comment]
So it's much about smooth client-side movement - can't blame Mojang for that, though it's getting potentially nasty to support on our side.

We're touching the question, if we have to implement (almost) fully featured moving checks for horses, boats, boats on horses, pigs...
* Specific speeds, also depending on medium. Do note this includes speed attributes, which we might still not even have Bukkit-API methods for.
* Jumping envelopes/slopes.
* On-ground/similar judgement.
* Lift-off-media conditions.
* Medium-transitions (usually nasty).
* Velocity handling, piston and block change handling (~lol?).
* Set-back handling. (potentially nasty, having to dismount/re-mount for teleportation, posing all sorts of potential trouble, also with other plugins like 'no dismount here' guards).
* The other lot.

To avoid overly complex redesigns at first, we might try something comparably simple first, which also could serve as a  fly/hover check for players (can't tell if it would mean a simplification or an extension rather...), like counting in-air time/phases and relating such to damage events and velocity amounts dealt, including basic accounting for gravity. All quite coarse, but possibly allowing to detect hover/fly while also preventing abusing small velocity amounts, such as are dealt with ordinary damage. Still speeding and medium-affinity are not so small points to cover, so i am not convinced that this would be fun in the first place.

Unfortunately we just had some data loss incident, so some progress is lost. With rather complex changes at stake, it's perhaps time to make some kind of transition to a more flexible and inviting check system, in order to get more developers involved - not sure the old checks can be transformed at low cost.

The options that i see right now are: 
* Feature freeze concerning anything 'old style' + cut down anything non-essential/in-the-way-of-something. Continue with strict rules for what can be done on old/new checks/infrastructure. This means cncp will be strictly discontinued, in favor of having developers of other plugins get in touch for compatibility issues (there are various options, no big deal IF others are willing to cooperate too).
* Forming a team of _developers_, not necessarily with me being the manager, in order to be able to support the more or less necessary coverage of things. This demands others being able to contribute directly, in terms of contributing such that i don't need to (re-) write all code. Would likely involve a redesign of the core infrastructure and possibly starting from scratch once more (easier check registration at any point of time, central registries for data and configuration, other).
* Call it a day with Minecraft.

Without achieving a balance of 'getting somewhere' vs. time spent, this is done.

**Comment by Cryptkeeper** [comment]
Even separating checks into smaller, more manageable (and debuggable) pieces would be greatly beneficial for people getting started on the platform. I've recently started diving into the NCP source to try and debug specific issues between edge cases with our servers and the checks. However the size and complexity of the checks is vast; which makes it difficult to edit and debug them without breaking many other things.

Being able to prototype potential fixes/new checks with NCP is incredibly important, but seemingly difficult unless you're deeply familiar with the structure.

Just my 2c 😄

**Comment by asofold** [comment]
Possibly details in here: https://gist.github.com/asofold/dde86d65604c8cb4cdb5461e9a48642c

All in all the amount of things we need to both cover essential cheats and maintain playability  (reduce/prevent false positives) is extensive. So what will i do:
* Transition to the next project phase (planning future or not future).

During the transition to the next project phase i'll attempt the following:
* Remove CompatNoCheatPlus, in favor of working together with other developers rather, if they cooperate. Testing with external plugins should be done by users/others, we might supervise/interpret debug logs to give hints, but can't dig into stuff. The advantage for all involved will be, that in future any compatibility thing will be either built into NCP directly (rather reflection, can't include other plugins as dependencies), or they will be built into the other plugin that had previously been incompatible (thinking of cncp removed).
* NCP: feature freeze + fix freeze, unless for show stoppers.
* If we need legacy checks - cover the minimum (e.g.  vehicle-fly), make code usable for multiple contexts (e.g. special speeding checks run with both players and boats).
* Focus on new types of core design and infrastructure as much as possible.

**Comment by asofold** [comment]
Current issue+show-stopper:
* Test how/if vehicle set-back works at all. Currently using a maximum horizontal speed for boats, which is set so low, that it triggers deterministically at some point. Current result: set-back loop + boat moved wrongly. Horizontal speed is used, because it doesn't need extra additions for quick testing. Increased logging, test variants of how to teleport. This likely is an issue with the old morepacketsvehicle check as well.

Future issues:
* Teleporting seems to need ejecting the player from the vehicle and setting them as passenger after teleporting both the vehicle and the player. This leads to the events for players exiting and entering the vehicle, which can be a problem with cross-plugin compatibility, e.g. if another plugin is to prevent entering/exiting vehicles.
* If we can't teleport using Bukkit, be it due to other plugins preventing it, or due to it just not working, there might be alternatives.
 * Try to do it with nms without firing an event. Likely impossible.
 * Try to work around with (partly fake) packet sending, both incoming and outgoing, cancel wrong incoming packets. See below for hard depending on packet level for essential vanilla features.
 * Work out some concept for additions to Spigot that might enable us to do what we need to do.
 * Kick the player and teleport the vehicle then.
 * A mixture of the above.

From there on rough schedule:
* Proof of concept horizontal speed limiting, just for some maximum thing, possibly including potion effects for living entities.
* Work towards limiting jump height for living entities.
 * Proof of concept with a maximum jump height, not accounting for effects.
 * Needs adding an extra set-back location for vehicles: last ground. Might lead to refactoring towards a set-back location storage/manager, with the ability to maintain multiple set-back locations including "age", to be used both for player and vehicle moving.
* Proof of concept fly check (assume jumping from last ground, and account for distance taken since assumed maximum y point). At first not accounting for anything like velocity (could become a show stopper, since we might not have velocity events for horses).

If we have to go to the packet level to support essential minecraft features, this could mean a lot of trouble. It would mean to hard-depend on ProtocolLib, which is not such an issue, but it would also mean a new stage of things. It would increase the complexity of implementation, likely having to synchronize packet level (asynchronous to the primary thread) with Bukkit events (primary thread). The synchronizing part means to account for the primary thread being at an arbitrary processing stage at the point of packet arrival, having an arbitrary amount of packets still in the queue for processing,  before a related Bukkit event would even fire. We'd likely have to precisely assign packets to events (and/or vice versa), possibly having to decide if to cancel/alter an incoming or outgoing packet, accounting for latency and for all sorts of effects that the server may have on the matter, such as kicking, other plugins doing stuff. That would add to complexity and time consumption a lot.

Questions to others:
* Is horizontal speeding an issue or a potential issue with the possibilities Minecraft 1.9.x offers to client developers? Horizontal checking will be kept very coarse for now, just in case, and in order to test vehicle set-back on 1.9.

**Comment by asofold** [comment]
Important questions:
* Is horizontal speeding an issue or a potential issue with Minecraft 1.9.2? Do consider having the morepacketsvehicle check activated.
* Are people really sure that living entities are really fully under control of the client? Spigot doesn't fire any events for those, so this would demand changes on server-side.

**Comment by GlitchHead** [comment]
@asofold with NCP enabled This seems to work with horses but the player gets kicked for flying unlike the boat it seems it does not work with pigs.

**Comment by asofold** [comment]
A deleted comment indicated that the cheats seem to "work" on horses as well, but players using it on horses might get kicked by the built-in vanilla fly check.

The issue with that might be, if the vanilla fly check for players is interfering with the NCP fly checks for players, so it gets disabled. If that switch also controls the vehicle part, we'll have the same kind of problem.

For now i'll do the boat thing then and see what other input we get.

**Comment by asofold** [comment]
Build 961 contains an attempt to  prevent some of boat flying. It's marked as 'failed' on the Jenkins server, due to not being able to deploy the artifacts to the maven repository , but the jar file is there.

**Comment by Dimatert9** [comment]
Fly still work. Compiled from latest source on my computer. And on Build 961 from Jenkins.

**Comment by asofold** [comment]
@Dimatert9 Only boats are covered right now. Has this been with boats? (I switched to another method after preliminary success, due to false positives, but will try with accounting for some obviously necessary workaround-ism.)

**Comment by MyPictures** [comment]
Hi @Dimatert9 I am not able to reproduce the bypass like it is shown on that video with NC+ 962. Have you tried to test it on a clear setup? Did you do modifications on the config?
What version of Spigot do you run?

**Comment by Dimatert9** [comment]
http://pastebin.com/Ef5uKaRd

compiled from lastest source on my computer.

**Comment by Dimatert9** [comment]
now work.
https://www.youtube.com/watch?v=Ig9WFReuonM&feature=youtu.be

**Comment by MyPictures** [comment]
@Dimatert9 Please post the output of /ncp version
in here so that I can setup a similar setup. 

Attaching another Log with 964 here (flying up a waterfall but not able to leave water with a boat):
[NCP-SF-Evlope (Waterfal up).zip](https://github.com/NoCheatPlus/Issues/files/244157/NCP-SF-Evlope.Waterfal.up.zip)

**Comment by Dimatert9** [comment]
https://i.gyazo.com/530209258e11ca856a572c8ff5897fbe.png

http://pastebin.com/QcRd2xVc

**Comment by asofold** [comment]
Looks like @Dimatert9 has a variant of flying that bypasses VehicleMoveEventS in total. In addition to the trouble there is no teleport events for vehicles. All this is pretty ridiculous, as that seems to be the vanilla checks allowing them to fly, bypassing plugins. This hardly will be going anywhere, if plugins aren't allowed to take control over vehicle moving (useful information on events, all events, teleport events). 

Look at this: 
16-05-01 19:31:40 [FINE] [MOVING_VEHICLE] [Leymooooooooooo] Vehicle update: BOAT Location{world=CraftWorld{name=world},x=-167.53068546547325,y=64.49850000089407,z=141.92048912707864,pitch=0.0,yaw=127.22132}
16-05-01 19:31:41 [FINE] [MOVING_VEHICLE] [Leymooooooooooo] Vehicle update: BOAT Location{world=CraftWorld{name=world},x=-167.13832837485728,y=62.523264312790474,z=143.7726283035339,pitch=0.0,yaw=73.125}
16-05-01 19:31:41 [FINE] [MOVING_VEHICLE] [Leymooooooooooo] Vehicle update: BOAT Location{world=CraftWorld{name=world},x=-166.32541144262424,y=66.41850000268221,z=140.59144514763221,pitch=0.0,yaw=148.34358}

The current implementation doesn't account for that type of bypass, but we'll eventually switch to giving the vehicle update event priority, assuming from->to ourselves, mostly skipping VehicleMoveEvent processing. We  still can't know when vehicles are teleported by other plugins or the server, which means all sorts of trouble.

**Comment by asofold** [comment]
I don't want this to look like being overly pessimistic or looking down on Mojang/Spigot in any way. The stuff to cover is not really (beginner-) friendly, in addition it is time consuming to test changes both for effectivity on cheats and for false positives, and all the anti cheating plugins i have come to have heard about, have been struggling to even support "basic" features of vanilla Minecraft, even after being there for years, or they have been resorting to obscure methods not fit for open source (much snake oil potential). Things keep adding up, and we/i are/am lacking the man power (me*(2...3]) to cover basic aspects within reasonably short time (for free, while not spending obscene amounts of time). 

So of course we all have already arranged with switching from 'reasonably short' to 'reasonable amounts of' time, thus i'll attempt to keep going with adding in potentially future-savvy internals while potentially patching things. This means that i am slower than with the hands-on-fix-it-now approach, but i hope to cover some ground within (...) reasonable time.

Since typing takes so long, i'll state what i'll do:
* Use VehicleUpdateEvent and keep track of past positions ourselves, instead of relying on the VehicleMoveEvent (not much magic, but since clients are much more in control, this is obligatory).
* Estimate if a position we encounter may have resulted from a server side set-back (moved too quickly, moved wrongly), by comparing the location with past location(s).
* Same way estimate, if other plugins might have teleported entities, by excluding past positions, and by having the distance exceed the thresholds for the server side teleports (this is flawed, if the server side stuff is disabled, so assume other plugins don't exist :p).
* Just skip processing VehicleMoveEvent, track consistency by keeping track of past update locations, and having nms entity fields accessible (~thanks Spigot).
* Get in touch with spigot developers, to add in events for teleportation of entites by both plugin and server, and perhaps (now that we are at it.-...) also for server-side set-backs for players (events exist, but a teleport cause other than unknown would be nice to have).

**Comment by asofold** [comment]
Build 970 represents an attempt to track positions for all types of vehicles. An actual fly check is only implemented for boats (a weak version, but it might work).

This implementation exclusively relies on our own vehicle past move tracking, and it ...
* can not detect server side vehicle set-back, thus there might happen set-backs by NCP directly following such.
* does not protect vs. tandem flying (does it exist?). Might also not cover enter-move-exit-repeat cheat attempts.

So i'd be interested if/how the check covers current boat fly cheats and if there are false positives.

**Comment by asofold** [comment]
Should be build 971, if you're not on 1.9.4 yet.

**Comment by asofold** [comment]
Switched to teleport from within event handling on vehicle set backs with build 972. Looks like that helps with set-back loops.

There's work left with not erasing our own set-backs, so we'll need to somehow detect them on vehicle enter.

Feedback on boat-fly much welcome, needed for progress.

**Comment by MyPictures** [comment]
Test results of BoatFly with 972 on Hambörger:
[w31BoatFly972.zip](https://github.com/NoCheatPlus/Issues/files/266142/w31BoatFly972.zip)

[15:19:35 INFO]: ---- Version information ----
[15:19:35 INFO]: #### Server ####
[15:19:35 INFO]: git-Spigot-e6f93f4-935f18b ~MC: 1.9.2~
[15:19:35 INFO]:   detected: 1.9.2
[15:19:35 INFO]: #### NoCheatPlus ####
[15:19:35 INFO]: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b972
[15:19:35 INFO]: MCAccess: 1.9-1.9.3 / Spigot-CB-1.9_R1
[15:19:35 INFO]: Features:
[15:19:35 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
[15:19:35 INFO]:   checks: FastConsume | Gutenberg
[15:19:35 INFO]:   defaults: pvpKnockBackVelocity
[15:19:35 INFO]: Hooks: AllViolations~NCP~ 1.0 | TestNCPHook 1.0

**Comment by asofold** [comment]
Build 975 represents the current state of things. Not much change check-wise, but set-back handling is altered to directly teleport from within event handling, in order to prevent set-back loops under certain conditions.

**Comment by MyPictures** [comment]
[BoatFly.txt](https://github.com/NoCheatPlus/Issues/files/298041/BoatFly.txt)
BoatFly movement dump:
18:47:50 INFO: ---- Version information ----
18:47:50 INFO: #### Server ####
18:47:50 INFO: git-Spigot-d20369f-7fc5cd8 ~MC: 1.9~
18:47:50 INFO: detected: 1.9
18:47:50 INFO: #### NoCheatPlus ####
18:47:50 INFO: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b987
18:47:50 INFO: MCAccess: 1.9-1.9.3 / Spigot-CB-1.9_R1

18:47:50 INFO: blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
18:47:50 INFO: checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
18:47:50 INFO: defaults: pvpKnockBackVelocity
18:47:50 INFO: packet-listeners: DebugAdapter | UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
18:47:50 INFO: Hooks: AllViolations~NCP~ 1.0 | TestNCPHook 1.0
18:47:50 INFO: #### Related Plugins ####
18:47:50 INFO: ProtocolLib v4.0.1

**Comment by asofold** [comment]
Speeding is interesting - i hoped for vanilla stopping that, but if we include reports about noclip with boats... it really looks like we have to provide almost the entire set of moving checks for vehicles, just like for players. Currently NCP would prevent horizontal speed above 4, because i didn't want to cause false positives, hoping for 'moved wrongly' or so.

**Comment by asofold** [comment]
Profane flying seems to be fixed, closing in favor of new tickets:
* Boats moving up a waterfall: https://github.com/NoCheatPlus/Issues/issues/194
* Vehicle speeding: https://github.com/NoCheatPlus/Issues/issues/195
* Rest of vehicle fly: https://github.com/NoCheatPlus/Issues/issues/196
