### ISSUE TITLE
Conflict with villager breeding

### ISSUE THREAD

**Issue by dunaland1** [NoCheatPlus/Issues#164]
If you have villager spawn eggs and use them they spawn normal villagers, but when you use the egg on a villager it should spawn a baby villager but it doesn't. This happens to other mobs - their eggs don't spawn baby mobs. If the player is in creative mode however - baby mobs appear.

I am curious which check is causing this so I can disable it

**Comment by dunaland1** [comment]
I believe it is NoCheatPlus because when I disable it everythign works. I am not however 100% sure that it isn't conflicting with another plugin so if you need I will post plugins list

**Comment by dunaland1** [comment]
Also I had problems with normal villager spawns - they were unable to reproduce. Disabling fastconsume check fixed this.

**Comment by asofold** [comment]
You could enable this be disabling the items check, setting checks.invenory.items to false, if i am right. That check is for most a legacy patch which needs renewing/confinement.

**Comment by asofold** [comment]
It's odd though, how fastconsume should relate to monster eggs. Individual items could also be blacklisted for that checks (items section, note the whitelist flag, false means the items in the list are not checked, use id or bukkit name ~ not sure it's MONSTER_EGG right now).

Has this changed with spigot updating? Or have you kept fastconsume off since then?

**Comment by asofold** [comment]
Assume fixed / or fixable via configuration (whitelist).
