### ISSUE TITLE
error - INVENTORY_OPEN

### ISSUE THREAD

**Issue by mat41997** [NoCheatPlus/Issues#168]
logs
http://hastebin.com/etiyozicaz.avrasm

**Comment by MyPictures** [comment]
Hi @mat41997

Thank you for your report. Please follow the template for issues: https://github.com/NoCheatPlus/Issues/blob/master/CONTRIBUTING.md
Server and NC+ are really important to solve the issue quicker.

**Comment by asofold** [comment]
The plugin UltraCosmetic (or similarly named) appears to teleport players in another thread than the primary server thread. Asynchronous Bukkit API access is dangerous in several ways and should not be used. This can lead to inconsistent data states or crashing your server, also because other plugins will not account for these kind of standard events to fire off the primary thread.

So my suggestion is to report to the plugin developers of ultra cosmetics and ask them to look into it...

**Comment by asofold** [comment]
Closing as 'can't fix' for said reasons.
