### ISSUE TITLE
ignoreallowflight = true -> fall-dmg with /fly

### ISSUE THREAD

**Issue by Platinteufel** [NoCheatPlus/Issues#171]
After setting ignoreallowflight = true my players getting fall-damage if they have /fly activated and stop flying (pressing 2 times space).

[00:51:37 INFO]: ---- Version information ----
[00:51:37 INFO]: #### Server ####
[00:51:37 INFO]: git-Paper-720 ~MC: 1.9.2~
[00:51:37 INFO]:   detected: 1.9.2
[00:51:37 INFO]: #### NoCheatPlus ####
[00:51:37 INFO]: Plugin: 3.14.0-SNAPSHOT-sMD5NET-b960
[00:51:37 INFO]: MCAccess: 1.9 / Spigot-CB-1.9_R1
[00:51:37 INFO]: Features:
[00:51:37 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9
[00:51:37 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[00:51:37 INFO]:   defaults: pvpKnockBackVelocity
[00:51:37 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter
[00:51:37 INFO]: Hooks: AllViolations~NCP~ 1.0
[00:51:37 INFO]: #### Related Plugins ####
[00:51:37 INFO]: ProtocolLib v4.0.0-SNAPSHOT-b273

**Comment by asofold** [comment]
Is this new since 1.9 ? Players used to not take fall damage with allowFlight set to true.

**Comment by Platinteufel** [comment]
AllowFlight is set to false in Server.properties, but that wasn't a problem before I've set ignoreallowflight=true.

**Comment by asofold** [comment]
I was refering to the player capabilities, which can be set via the Bukkit API. If set by a plugin, players wouldn't take fall damage. There might be a change on that account.

If it can be reproduced systematically, it could pay to try with being exempted from the nofall check, e.g. with ncp exempt [PLAYER_NAME] MOVING_NOFALL  (ncp unexempt [PLAYER_NAME] to remove).

Otherwise the server.properties setting currently does help with vehicles, as we don't cover those fully yet. It might allow other stuff on ordinary moving, in terms of interfering with current checks. Once vehicle checks are confirmed to work, it can be disabled again.

**Comment by Platinteufel** [comment]
Okay, thanks! And was does allowflight specific do? Does it not open up possibilities for fly-hackers? I don't want my players to fly, just fix the elytra thing.

**Comment by asofold** [comment]
Wait a second :).

The issue this ticket is about, is that player receive fall damage for landing with elytra on, when ignoreallowflight is set? That would be quite a different thing...

Currently the allow-flight setting in vanilla should probably be set to false, until we have a working vehicle fly check.

The ignoreallowflight setting in NCP concerns a Bukkit-API specific topic, since you can explicitly allow individual players to send the double-jump thing to start flying.  If this is about elytra, i am not sure how that should be related, so we should clarify now...

**Comment by Platinteufel** [comment]
It's not about elytra. :) As soon as I set ignoreallowflight=true in ncp config, my players getting fall-dmg with essentials' /fly activated. And this is definitely because of changing this setting, because it doesn't happen with ignoreallowflight=false.
The vanilla setting allow-flight is set to false in Server.properties, I didn't changed anything here.

**Comment by asofold** [comment]
Ok, good, just so i don't get confused here.

**Comment by Platinteufel** [comment]
Now I've set allow-flight = true AND ignoreallowflight = true and my players getting fall-dmg .. that's quite annoying. :/

**Comment by asofold** [comment]
But the fall damage is not dealt, if you disable NoFall, or if you set it to not deal damage (much similar effect, because disabling proactively dealing damage allows cheating basically).

**Comment by Platinteufel** [comment]
Nope, if I disable NoFall it's not happening any more.

**Comment by asofold** [comment]
Damn :). Do you happen to have a (on-the-fly) debug log of such an incident? Can it be reproduced at will? Can you reproduce @MyPictures?

**Comment by Platinteufel** [comment]
Video: https://youtu.be/DQXHhLKWsRI
debug logs (matching to the video): https://paste.ee/p/5XzCT

**Comment by asofold** [comment]
Looks like the players are taking fall damage where they hadn't on previous versions of Minecraft. Need to reproduce with differing MC versions. I do have a concept for fixing though.

**Comment by Platinteufel** [comment]
Just tested it in Minecraft 1.8 & 1.7 .. same situation, players also get fall damage with /fly

**Comment by asofold** [comment]
Could also be caused by a more or less recent change in NCP for fly-nofly transition (though the conception of that was to reduce issues for the transition).

Currently the log looks like the players are actually falling (not flying) and then take fall damage naturally.

If you could create another debug log with the upcoming build, it would help clarify a couple of things. That would be build 980 +.

**Comment by Platinteufel** [comment]
Here we go: http://pastebin.com/bBaHpPzD

**Comment by asofold** [comment]
Great! Looks like it's not hard to reproduce. However on Spigot (protocol) build of 1.7.10, i don't take fall damage with being allowed to fly, but not actually flying. Perhaps it's been on PaperSpigot back then?

In any case i'll attempt a workaround, that allows turning that off. In fact i always wanted to have fall damage with players who are allowed to fly, because it needs more skill with flying turning off under certain circumstances :p. I'll make it so it'll not deal damage by default with players who are allowed to fly.

**Comment by asofold** [comment]
Build 981 contains the fix attempt to not deal damage with players who are allowed to fly.

It can still be configured, so in theory one could still enable fall damage for special features, e.g. per world.

**Comment by Platinteufel** [comment]
Seems to work fine, thank you very much!
