### ISSUE TITLE
Passable check prevents players from standing on slabs, going through doors, etc. in 1.9.4.

### ISSUE THREAD

**Issue by ThierryKamber** [NoCheatPlus/Issues#173]
When using the latest build of NCP together with the new Spigot build for 1.9.4, players fail the Passable check when they try to step on a slab or go through a door, etc..
**It seems like NCP currently "sees" those blocks as full solid blocks.**

How to reproduce:
1. Use the latest successful Spigot and NCP builds at the time of this report.
2. Place a half slap and try to step on it.
3. NCP will report something like: "Player failed Passable: moved into a block [...]".

**Comment by Kulkinz** [comment]
Another block that has the issue is Iron Bars

**Comment by asofold** [comment]
Please just post the output resulting of the 'ncp version' command instead of 'latest'. No one will be able to assign versions after a couple of days/updates :).

Currently "latest" is build 967 (thanks md_5 :p), which contains [BLEEDING] 1.9.4 support. Be very careful after updating to continue checking for issues and updates for all (relevant) plugins + server.

**Comment by ThierryKamber** [comment]
We updated to build 967 in the morning which should be applied (if not already) on the next restart.
I will update this as soon as I know if this fixed the problem or if it persists.
Before the update, we were using build 965 by the way.

**Comment by asofold** [comment]
The block shape stuff should be mostly resolved, i can only do so much testing.

1.9.4 is another update that changed internal package naming so an update for the compatibility layer of NCP was necessary. The update of the compatibility layer is mixed with other recent changes, which may or may not make things more shifty. The other changes concern vehicles rather.

**Comment by antain** [comment]
For me this issue happens when i compile ncp from sources with maven. When i get it from ci all works fine.

**Comment by asofold** [comment]
@antain This is due to NCP building the minimal profile by default. To have native access, you need to specify a build profile (and might also need to specify a build parameter, depending on environment). For reference please have a look at the readme.md of  the NoCheatPlus project: https://github.com/NoCheatPlus/NoCheatPlus/#compiling-nocheatplus

**Comment by ThierryKamber** [comment]
The issues with the passable check seem to be resolved now. :)
Closing this.

**Comment by asofold** [comment]
Thanks.

**Comment by codergautam** [comment]
Im having this issue still
