### ISSUE TITLE
Error plugin

### ISSUE THREAD

**Issue by JabloPhil** [NoCheatPlus/Issues#175]
Hi, I ran into the same problem: http://pastebin.com/VQn2x6Vp
Counting on your help!
![q](https://cloud.githubusercontent.com/assets/19308053/15183938/d7a4546a-17c5-11e6-970c-b8393a80069e.PNG)

PaperSpigot 1.8.8
version: 3.13.7-RC-sMD5NET-b925

**Comment by asofold** [comment]
Is there a web page for that mod? Do they support the server communicating feature support?

**Comment by asofold** [comment]
(Previous comment deleted, wrong issue.)

This is funny :). Apparently A player is kicked, ncp closes the inventory and the player is kicked again during the InventoryCloseEvent, while the state of the inventory is not being changed during the nested calls.

It'll be futile to discuss whom to move first, because both plugins (WorldGuard and NCP obviously don't detect nested events here. I'll attempt a quick fix.

**Comment by asofold** [comment]
Dix attempt in build 968. Note that there are other changes that might hide a couple of bugs elsewhere ~ bleeding edge.

**Comment by JabloPhil** [comment]
Well, thank you :)

**Comment by asofold** [comment]
So i assume the fix works? I 'll close the ticket in an optimistic way then!
