### ISSUE TITLE
What is the best way to change the NC+ setback position?

### ISSUE THREAD

**Issue by Vinc0682** [NoCheatPlus/Issues#177]
Hey there,
as the title may already have told you, I was wondering how to drag down players suspected for survival-fly / change the setpack position, I've already got this code hacked to together :smile: 
`@Override
    public boolean onCheckFailure(CheckType checkType, Player p, IViolationInfo vlInfo)
    {
        if (!isEnabled())
            return true;
        if (checkType != CheckType.MOVING_SURVIVALFLY)
            return true;
        if (p.hasPermission("ntac.bypass.ncp-dragdown"))
            return true;

```
    if (vlInfo.willCancel() && !PlayerUtils.isPlayerOnGround(p))
    {
        //p.sendMessage("Changing setback position");
        Location loc = p.getLocation().clone();
        loc.add(0, -0.1, 0);
        if (loc.getWorld().getBlockAt(loc) == null)
            p.teleport(loc);
        return false;
    }
    return true;
}`
```

Players still got dragged back to the NC+ setback-position :(

**Comment by Vinc0682** [comment]
Fixed it myself, teleporting works.

**Comment by asofold** [comment]
Teleporting is problematic though, because one can't assume all plugins to handle "teleport during handling player move" well.

There can be alternatives, though ultimately NCP should be adapted to allow this from the PlayerTeleportEvent, allowing to distinguish if this is a vehicle set-back or a player set-back or none at all.

Currently probably the best method is to combine an NCPHook with listening to PlayerMoveEvent on EventPriority.LOW.
* Hook: Tell your PlayerMoveEvent listener that the player is going to be set back by survivalfly (possibly store uuid).
* PlayerMoveEvent listener, if told to act: 
 * Reset the 'act' notice.
 * Get the MovingData (data) and MovingConfig (cc) for the player.
 * Verify that this actually is a set back (data.isTeleported(event.getTo())). If not... reset+abort.
 * Find the desired target location (newTarget).
 * data.setSetBack(newTarget); // To have your new location be the set-back from then on (!).
 * data.prepareSetBack(newTarget); 
 * NCPAPIProvider.getNoCheatPlusAPI().getGenericInstance(AuxMoving.class).resetPositionsAndMediumProperties(player, newTo, data, cc);

There is no need to clone locations on passing to data.XY. Perhaps for event.setTo one might, unless the location is created there and not stored anyway.

Of course teleporting should work with NCP, and also is less likely to break. You might still use data.setSetBack to ensure the player is set back there in future (though that's the part that might break if we do the same with player set-backs like we did with vehicles).

**Comment by asofold** [comment]
NoCheatPlus has been changed to cancel moving events on MC 1.9 and later. To enable that for MC pre-1.9, configuration would have to be changed, it would also cause more freezing in case of set-backs, false-positive or check failures.

Point being with using cancelling, you could listen to the PlayerMoveEvent on EventPriority.HIGHEST (or anything between LOWEST and MONITOR) and in case of the event being cancelled and MovingData.getData(player).hasTeleported(), you could use setTeleported(otherLocation) to set teleport to a different location. If you're very sure about that location, you could also set the actual set-back location with MovingData.setSetBack, but that might be possible to ommit anyway. For some cases this could also be an incoming move, from before the client noticing the set-back, so data.getTeleported or isTeleported may return your own set-back after you've set it, depending on timing.

I'm currently looking into the possiblity of a coarse force-fall thing (not enforcing velocity/speed at first) - later a tp-to-ground-underneath also is thinkable. 

Technically this all would be more nice with having a different method of checking for on-ground (distance-to-ground with max. margin, instead of isOnGround with margin), all with pros and cons, though.

**Comment by asofold** [comment]
If this is about NTAC, sorry for the delay :p. Closing as resolved, as this should be a good enough coverage for the moment.

**Comment by Vinc0682** [comment]
Since I abadoned NTAC a while ago, you don't have to be sorry about the delay. However, props to you for still answering a nearly one year old issue.
