### ISSUE TITLE
Second passenger of a boat gets teleported back to entering location

### ISSUE THREAD

**Issue by Black-Hole** [NoCheatPlus/Issues#207]
How to reproduce:
- place a boat
- let player A enter the boat
- let player B enter the boat, too
- let player A move the boat over some distance
- let player A disconnect
- Player B will now be the first passenger

The problem:
The boat including player B gets teleported back to the location where player B entered the boat.
(Sometimes the chunks around the player are not updated so looks weird to him.)

Expected behavior:
Player B should remain in place and be able to control the boat.

Displayed violations for player B:
NCP: [22:46:36] vehicle.vehicleenvelope VL 2  (n2a1m1)

**Comment by asofold** [comment]
I was waiting for this one.

Looks like the best we can do is to attempt to ignore the passenger who can not steer the boat, though i don't know if not both could. Problem being that the Bukkit API doesn't give us any cluse about multiple passengers. Thinkable workarounds are problematic too, because of latency (we end up looking for potential passengers within 12 blocks range or so).

I will need a debug log (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players - lots ouf ouput) to get closer to why exactly it's prevented.

**Comment by Black-Hole** [comment]
Here is the log file:
http://pastebin.com/3gMiwUks

The last messages keeps repeating itself.

**Comment by asofold** [comment]
(Need to find a way to reliably detect passengers.)

**Comment by Black-Hole** [comment]
Since Spigot 1.11.2 there is now a Entity.getPassengers() and some other methods:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/a17b015899fd9a82d63b61c5a37a52ecbfb89b9e

**Comment by asofold** [comment]
Perfect, thank you :).

**Comment by asofold** [comment]
Build 1070 (cough) contains experimental additions. Untested, risky - if someone could test that with two passengers like described above (and possibly other combinations including destroying the boat somehow, while two players are inside), that would be really helpful.

**Comment by asofold** [comment]
Assume fixed around build 1071/1072, shortly tested. Please comment / reopen if not, could've missed higher latency issues.
