### ISSUE TITLE
SurvivalFly disable teleport back

### ISSUE THREAD

**Issue by MClausz** [NoCheatPlus/Issues#216]
I'm having a problem with anti survival fly
For example a player playing a parkour map, when they jump miss, turn on flight hack while floating and NCP will revert them to the previuos block where they stood before jumping instead of falling down.
Any sollution?

**Comment by asofold** [comment]
Should duplicate this ticket: https://github.com/NoCheatPlus/Issues/issues/8

Currently it's not possible. We set back to the last ground position, because (with dealing fall damage) it yields the fewest types of abuse, in terms of not allowing players to get anywhere with cheating where they otherwise couldn't. 

I'm well aware that that is not optimal for parkour. We'll probably add an option to make this possible.

**Comment by MClausz** [comment]
please fix this asap, I really need this to be fixed. Thanks!

**Comment by jonesdj1** [comment]
fixing this would make it easy for fly hacks to be made as plugins like aac have it patched and have fly bypasses made almost weekly

**Comment by asofold** [comment]
This ticket: https://github.com/NoCheatPlus/Issues/issues/8

I've always been aware of the abuse potential for in-air and to-ground set-back paradigms. What NCP does, will allow you to get back to the last ground position, but it als prevents players from getting anywhere where they could otherwise not get.

A not-so-good example is a long tunnel downwards with a lot of pistons pushing in and out, and water way below, such that it's impossible to ever fall through without hitting a piston (think of 200 blocks fall distance and a piston-based ground every so and so blocks. A cheater could get into the water by faking a violation at the moment when theyre still high, but when no pistons barr the way for a split second.

That's just an example to illustrate one of the issues, it's a 'bad example', because it should be very hard for the client to get the timing right, and they'd die if they don't manage to get through (on the other hand it could be a parkour dead-end which players need to skip, setting them back to a checkpoint if they fail) - the other reason is that with upcoming pistons support, cheaters will certainly be able to fall through the blocks simply, because there would have been air just a moment ago.

In fact for parkour i'd really opt for a checkpoint plugin/interface. It could be built into NCP to support overriding the set-back or  to actively set a checkpoint to be used instead of any set-back locations.
