### ISSUE TITLE
Everyone gets notified...?

### ISSUE THREAD

**Issue by AndrewRed67** [NoCheatPlus/Issues#217]
Hey, I'm not sure if this is the place to ask this,
but I have a small issue, everyone gets notified by NCP, but I negated these permissions for the normal ranks;
- -nocheatplus.admin
- -nocheatplus.admin.notify
- -nocheatplus.notify

We are running version;
![image](https://cloud.githubusercontent.com/assets/20109293/16302196/1af3d7e0-394a-11e6-8217-56547a1522a9.png)

Is there any reason why everyone gets the message, and not only the groups with the permissions for it?
Thanks in advance. :)
-Andrew

**Comment by asofold** [comment]
This seems to happen on rare occasions. We assume it's related to permisisons plugins and/or other. At least there should be no need to negate permission nodes of NCP for normal users, they should not see anything anyway.

For one thing, is your ProtocolLib up  to date for 1.10? There should be 4.0.2 out there...

Otherwise i'd be interested in permissions plugin(s) or possibly a plugin list  (+ versions).

**Comment by AndrewRed67** [comment]
Hello asofold,
This is the list of our plugins, we use the PermissionsEx plugin version 1.23.4, ProtocolLib version 4.0.2.

![image](https://cloud.githubusercontent.com/assets/20109293/16314540/a7a1ffee-397e-11e6-86f6-002d2e90a4cd.png)

I hope that you could find a reason why it doesn't work...

**Comment by AndrewRed67** [comment]
Hello,
We just tried some few things, and we don't know exactly what we've done, but it probably works just as needed. I'll leave this issue open, just in case there are still a few problems. :+1:

**Comment by asofold** [comment]
Sure ...

**Comment by Platinteufel** [comment]
Why do you negate these permissions? People don't have them by default. I bet this was a permission issue.

**Comment by asofold** [comment]
Assume superseded by permissions configuration / updating.
