### ISSUE TITLE
A Very Big Bug About checks.moving.survivalfly

### ISSUE THREAD

**Issue by ASuperthings** [NoCheatPlus/Issues#259]
Hello,
if setting the checks.moving.survivalfly to true,all players(except operators) could not move on the stairs,slabs or chest.
if I make no changes to the config,it will happen too.
Hope to fix quickly!
Thank you very very much!
NCP Vrsion:1022
Version:1.10_R1
Thank you again!

**Comment by Wealh** [comment]
Bump

**Comment by asofold** [comment]
Could you post the full output of the 'ncp version' command with every issue report? It really helps with judging quickly, allthough NCP version and server version are the most important - is it default spigot or paper or ...?

We'll need more details on 'can't move on slabs etc', because it reads like 'ncp not on 1022 for MC 1.10.2', but can't know.
* Is it all kinds of slabs/stairs or just "newer types like acacia wood xyz / end_something_..."?
* Can't move at all?
* Just issues with sprint + jump?

**Comment by ASuperthings** [comment]
The newest version.
It's all kinds of slabs/stairs...
If a player move on the slabs/stairs,they can't move at all.
All kinds of jumps

**Comment by asofold** [comment]
Could you still re-post the full output of the 'ncp version' command (including features and all)?

**Comment by Janmm14** [comment]
@asuperthings

**Comment by asofold** [comment]
suprse4ded.
