### ISSUE TITLE
Failed Passible 1.9 Doors

### ISSUE THREAD

**Issue by Typosch** [NoCheatPlus/Issues#269]
Players cannot go through doors without getting pulled back and the notification saying Failed Passible

**Comment by MarkElf** [comment]
Output of /ncp version please?

**Comment by Typosch** [comment]
**Here it is:**
http://imgur.com/a/Zi5f4
**Don't see what the problem is, should be the right version.**

**Comment by MarkElf** [comment]
Update to the following version:
http://ci.md-5.net/job/NoCheatPlus/lastSuccessfulBuild/artifact/target/NoCheatPlus.jar

**Comment by asofold** [comment]
Thanks for the support - indeed build 925 is too outdated. Since development is more active, using NCP build 1023 should be more appropriate. 

Of course i'll attempt to get an official release ready some time soon, but things need to be rolling first.

Closing, as the issue should already be fixed in later builds of NCP. Just note that the latest build might contain experimental additions, so always also consult the change lists linked at the top of http://ci.md-5.net/job/NoCheatPlus/ (e.g. http://ci.md-5.net/job/NoCheatPlus/changes) - don't lightly update past too young builds marked as [BLEEDING].
