### ISSUE TITLE
Kicked for flying when teleporting or getting a knockback

### ISSUE THREAD

**Issue by matgsan** [NoCheatPlus/Issues#285]
My players are getting kicked for flying or getting dragged back when they are knockbacked...
I am running a Spigot Server 1.8.8
Using a default configuration the latest version of NCP

**Comment by asofold** [comment]
Please always include the complete output of the 'ncp version' command with issue reports.

In this case we are missing what 'latest' means. The latest version of NCP fit for use anywhere, should be the latest development build on our jenkins site (right now, be wary with [BLEEDING] or [INSTABLE] changes, check on the changes list): http://ci.md-5.net/job/NoCheatPlus/

Currently development intensity is increased again and i'll attempt to make a release somewhat soonish.

**Comment by matgsan** [comment]
Using this version
http://prntscr.com/d5l0nk

**Comment by asofold** [comment]
A "related plugins" section is not present or is it cut off (in the 'ncp version' output)?

So the issue persists on the latest development builds? Do issues  happen often or rather seldomly?

**Comment by matgsan** [comment]
Often, i needed to make survival fly just cancel after 3500 VL to solve this type of false positives and solve because the players were dragged back after knockback

**Comment by asofold** [comment]
That's pretty odd with build 1023.
* Are any multi client protocol support plugins in use?
* Are plugins in use that alter velocity somehow?
* Are you using ProtocolLib? If so, which version?

**Comment by i9hdkill** [comment]
Same thing, everything fine with Build 1018, now we updated to Build 1036 and players are getting kicked for flying or related if they are knockbacked into the air.

ncp version:
`---- Version information ----
[17:27:05 INFO]: #### Server ####
[17:27:05 INFO]: git-Spigot-455072c-43ab266 ~MC: 1.10.2~
[17:27:05 INFO]:   detected: 1.10.2
[17:27:05 INFO]: #### NoCheatPlus ####
[17:27:05 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1036
[17:27:05 INFO]: MCAccess: 1.10 / Spigot-CB-1.10_R1
[17:27:05 INFO]: Features:
[17:27:05 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
[17:27:05 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[17:27:05 INFO]:   defaults: pvpKnockBackVelocity
[17:27:05 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[17:27:05 INFO]: Hooks: AllViolations~NCP~ 1.0
[17:27:05 INFO]: #### Related Plugins ####
[17:27:05 INFO]: ProtocolLib v4.1.0-SNAPSHOT-b315

We are using Protocolsupport for allowing 1.8-1.10.2 and ViaVersion for 1.11 support.

But the issue is happening on all clients, even 1.10.2 (and protocolib is not touching 1.10.2)
When switching back to 1018, everything is fine again.
`

**Comment by asofold** [comment]
I could use more information (if possible):
* Violation messages (_ncp info playername_ before and after reproducing issues, better:  violation log entries with [tags] in the message of the strings section).
* Much better: If it can be reproduced at will by a player, debug logs of the player violating the survivalfly check could be very helpful (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players).

**Comment by asofold** [comment]
Superseded by everything (Spigot, Packet plugins, protocol support plugins, NCP). (...time)
