### ISSUE TITLE
Can't jump since last spigot update

### ISSUE THREAD

**Issue by zenandreas** [NoCheatPlus/Issues#293]
Few days ago we updated to the latest Spigot build and default players can't jump anymore.

**Comment by ultima84** [comment]
I can confirm I am having the same issue on my server.
I updated spigot and the next day players NCP was kicking players for survivalfly, despite them only jumping.
I was getting NCP violation notifications, I disabled checking for survivalfly and creativefly and it produced the normal "<player> moved wrongly!" message.
I then went and updated NCP to the latest version and no change.
Is this caused by a change in spigot?

I downgraded spigot back to the version I was using prior to the issues and the issue is gone. It appears something changed in one of the last 8 spigot updates that is causing this issue.

**Comment by orkun1675** [comment]
Having the same issue.

**Comment by asofold** [comment]
Does this persist as of now (can't reproduce)?

**Comment by Platinteufel** [comment]
https://github.com/PaperMC/Paper/issues/453

Fixed in the latest Paper builds. Haven't tested it with spigot yet.

**Comment by Platinteufel** [comment]
Should no longer be relevant since spigot reverted this commit.

**Comment by ultima84** [comment]
I updated to the latest spigot and NCP and am no longer having the issue.
