### ISSUE TITLE
GRASS_PATH is bugging players (same as lilypads was) on server with multiversion support (ProtocolSupport)

### ISSUE THREAD

**Issue by piter909** [NoCheatPlus/Issues#304]
GRASS_PATH is bugging players (same as lilypads was) on server with multiversion support (ProtocolSupport).
Addon dev of ProtocolSupport redirected me here with my problem:
https://github.com/ProtocolSupport/ProtocolSupport/issues/305#issuecomment-259376449
Thanks for any try to fix of this problem :P.

**Comment by piter909** [comment]
Will it be fixed in near future? :/

**Comment by asofold** [comment]
Sorry for the late reply.

* https://github.com/NoCheatPlus/Issues/blob/master/ISSUE_TEMPLATE (versions, what's the native server version, which client versions are supported, possibly ProtocolLib version?)
* For 1.11, block shape access is there, however i assume you're on an earlier version of MC natively, allowing higher version clients to join?

For multiple versions where players have different heights for blocks, you can't do much better than overriding block flags, e.g. try:
GRASS_PATH: solid+ground+ground_height+height100+xz100

If it should be necessary, i'll be able to add flags to confine minimum and maximum height more precisely here, though there'll always be potential for issues, because jump height will differ, which could affect judging horizontal speed with continuous jumping.

**Comment by asofold** [comment]
added a water lily patch activating with ViaVersion/ProtocolSupport.

This could be added too - i could make it so well have a height16_15  (0.0625 below full block) flag and let it all be interpreted, so they can stand between that and full block height.

**Comment by asofold** [comment]
GRASS_PATH, SOIL and WATER_LILY are contained in the multi protocol patch, enabling with certain such plugins. If you use that build, please test without having entries for these blocks in the compatibility.blocks.overrideflags section - would love to have some input here.

Build ~ 1136
