### ISSUE TITLE
Constant boat rubberbanding

### ISSUE THREAD

**Issue by FirstReplay** [NoCheatPlus/Issues#321]
#### Short description of the issue
Within a few seconds of using a boat, it begins to 'glitch out' and appear ahead of you and then start bouncing back and forth from under you. This also happens with minecarts but no where near as often as boats.

Video: https://streamable.com/l0dz
This happens with any client including vanilla.

#### NCP version
1040 + ProtocolLib 334

#### How to reproduce the issue?
Get in a boat and sail. Get in a minecart and go up or down an angle on powered rails.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No changes.

**Comment by MarkElf** [comment]
Providing the direct output of '/ncp version' would be great to identify what version of mc that you are running as well as additional information. Noting any protocol modifying plugins would be great as well, i.e viaversion, protocol support, etc.

To temporarily resolve your issue, I would provide players with the permission node: 'nocheatplus.checks.moving.vehicle.envelope'

**Comment by FirstReplay** [comment]
Thanks for the tip @MarkElf but that permission allows players to fly using BoatFly on hacked clients so unfortunately I can't enable that.

The output of '/ncp version' is:

`#### Server ####`
`git-Paper-959 ~MC: 1.11~`
`detected: 1.11`
`#### NoCheatPlus ####`
`Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1040`
`MCAccess: 1.4.5-1.11|? / CB-Reflect`
`Features:`
`blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11`
`checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency`
`defaults: pvpKnockBackVelocity`
`packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance`
`Hooks: AllViolations~NCP~ 1.0`
`#### Related Plugins ####`
`ProtocolLib v4.2.0-SNAPSHOT-b334`

There are no other protocol modifying plugins.

**Comment by asofold** [comment]
I can't watch that video (Firefox, NoScript, with and without indexed db enabled).

On plain water surface i can't reproduce on paper 959 + ProtocolLib 335.

With a water fall (very high, water just drops all the way down, after short horizontal moment), with PaperSpigot there will be rubberbanding + moved too quickly (i assume one of those infamous moved too quickly loops). This does _not_ happen with the original spigot server.

Could be that's the same issue, could be not - Are there boat [ + (vehicle of soandso)] moved too quickly messages on the server log, at the same time of the issues occuring?

**Comment by FirstReplay** [comment]
@asofold I am seeing a lot of those errors when the boats rubberband. But without NCP this issue does not occur and with the 'nocheatplus.checks.moving.vehicle.envelope' permission applied it also is resolved.

The only problem is, we still need checks on vehicles to stop BoatFly. Am I right in guessing this is why we get the same behavior with horses going up stairs (which results in moved too fast errors for the horse)?

Would perhaps being able to lower the NCP threshold for the checks be a good idea to enable it to be fine-tuned?

**Comment by asofold** [comment]
"moved too quickly" on the console is the server-side check, NCP can't influence that.

Worse, it looks like with PaperSpigot it leads to a set-back loop on occasion, while with default spigot it doesn't. Thus i could attempt to claim somethin like  "without paper this isn't an issue" :) - i'd like to resolve that issue somehow, though.

Horses moving upwards on stairs.... generate tons of "moved to quickly", typically _not related to NCP in any way_. I use to get that a lot on a local server with spigot with the stair-pyramids on my testing setup.

To repeat, with boats, i was able to get a moved-tooquickly-PLUS-ncp-set-back loop/thing only on paper with a water-fall-like setup.

**Comment by FirstReplay** [comment]
@asofold So if I understand correctly, this is an issue with NCP not being able to change the threshold? I would say it's clearly an NCP issue if disabling the check stops the rubbberbanding.

**Comment by asofold** [comment]
@FirstReplay Clearly ... not really.

PaperSpigot changed something with vehicle set-backs, so the NCP check keeps triggering, which NCP doesn't with latest Spigot and which NCP hadn't done on earlier versions of PaperSpigot.

Since vehicle moving is horrible server side all over, any changes to how things are done are very peculiar, and you can't easily blame it on plugins, which have to deal with all sorts of special cases and not-existing support on server side.

Thresholds are not really involved, it's rather prediction, in this case a 0-distance move is estimated (as there always is guessing involved in what is a move and from where to where it's leading :p), and NCP is triggering the "too slow falling" part of the vehicle.envelope check. Worse, the server adds "moved too quickly" teleporting, which NCP can't do much about.

So we have another special condition with PaperSpigot :). Of course i'll do something like 'detect 0-y-dist move after set-back', and i'll see if the server still adds extra "moved too quickly" teleporting. Currently other topics are on top, so some patience is necessary, especially since this doesn't seem to be the case with Spigot. After the next build busying about slime blocks and pistons and the like, i'll have a closer look at what i can change, or perhaps the next build contains a fix attempt already. ETA is some time this weekend, probably within the next 28 hours, but can't say exactly.

**Comment by RoboMWM** [comment]
paper.yml would be nice to see

As per brief conversation in #paper about this issue:

> [09:24:07] ~Z750: yeah I cant find any patch that makes the changes they're referring to
[09:24:21] ~Z750: maybe the tnt cannon patch, but if thats causing the issue the answer is to turn it off

**Comment by asofold** [comment]
Yes, please consider what @RoboMWM just posted here :).

(I meant non-existing support in terms of not having a more fleshed out access api for vehicle moving like with player moving, just in casse.)

**Comment by asofold** [comment]
Assume suprseded by both paper and ncp having updates at least with one of the both containing related changes (can't reproduce). Please note here or with in new issues, if issues persist.
