### ISSUE TITLE
Compiling in Eclipse

### ISSUE THREAD

**Issue by XenoGaming** [NoCheatPlus/Issues#329]
So I want to compile NCP in Eclipse but I do not know what I need to import into the src. I know I need like NCPCore and those stuff but what else?

**Comment by Janmm14** [comment]
Import outer pom as maven project. Use the profiles in the outer pom to let it choose the projects to build.

**Comment by asofold** [comment]
Importing the pom looks like it should work.

Note this for compiling: https://github.com/NoCheatPlus/NoCheatPlus/#compiling-nocheatplus

Typically on setting up the project newly i use to import the entire NoCheatPlus folder as general project, then convert to maven (possibly add the java nature ...), set source paths (.../java) for those projects i want to read source for (typically all), then i need to add dependency jars to read the code without errors displaying everywhere. I'm sure this is not elegant :). You also would need to install all dependencies you need to the local maven repository (see readme.md for reference, it can be done with eclipse too, provided you have the jars). Build profiles and parameters (might need both on Jenkins) help confine which dependencies are used.

Note that the reflection module is always in with the ncp_base profile/parameter, and should cover everything as well (just less performance). Currently for 1.11 there is no extra profile, because i haven't added a native access module yet, instead the reflection based module had been updated to work with 1.11.

**Comment by asofold** [comment]
Closing as superseded (by time passing by).
