### ISSUE TITLE
Godmode exploit

### ISSUE THREAD

**Issue by Janmm14** [NoCheatPlus/Issues#332]
#### Short description of the issue.
People teleport themself 10 blocks below current position (phase is triggered+setbacks). This turns the player into a godmode-like state. (They don't recieve damage). Only ncp movement derections were enabled. (No range/angle/whatever detection for the attacking player)

#### Complete output of the _ncp version_ command (please prefer text here).
build 1043 

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
aac 3, but it doesn't generate any vls for combat checks (movement checks of aac disabled)

Video: https://youtu.be/nm9HNup09O4
(Bader video: https://youtu.be/Xr5i0fTFws8)

**Comment by asofold** [comment]
Is this possible with aac 3 not being installed at all?
Running multiple anti cheating plugins alongside can be quite problematic, just in general.

**Comment by Janmm14** [comment]
I don't know and GommeHD doesn't want to mess with NCP more than needed. I don't want to start coding on a cheat client for testing such things out too.
Basically are you cancelling the playermoveevent in case of phase? else it maybe *could* be the issue that other checks/plugin have the wrong player position I *think* (I don't know)

**Comment by asofold** [comment]
For a production environment it would be difficult to remove something just fopr testing :). I can't know if you have players at hand who would de,monstrate their client (perhaps for an unban or so :p), so i tend to ask "if ... could ...".

Technically NCP can't cancel PlayerMoveEvent, because that means the server will teleport to the last recorded position. That is PlayerMoveEvent.getFrom(), which could/can not be overridden by plugins (concerning setCancelled(true)!). However that position is not fit for use as a set back location in general, e.g. we set back to "last ground", and if you used 'getFrom()' or setCancelled(true) for set back, you'd have to care for clients abusing THAT then - the basic reason for NCP using last ground instead is, that you could reach places you usually couldn't, e.g. due to removing the fall speed with a set back. Thus we use setTo(setBackLocation) with PlayerMoveEvent. We also avoid teleporting during PlayerMoveEvent handling. For vehicles we schedule a task for set-back.

Now text again ... if several plugins monitor moving without accounting for each other, they'll receive odd moves by NCP in case of set back. In general multiple plugins potentially setting back the player, all using different set back policies (last ground, event.setCancelled(true), ...) could lead to fly exploits too, at least to trouble :).

Now for the god mode, is there any hints about violations or server log messages, sequence of actions or other side conditions to trigger it or to happen after triggering it?

Perhaps i could add some kind of auto logging feature, but it only pays if we know some useful sequence of things (i'll read the description again, to see if that's already enough :) ).

**Comment by Janmm14** [comment]
@asofold 
Movement checks of aac 3 were disabled, they were causing too much false positives.
Well what was found in the logs was phasing exactly 10 blocks down. You could maybe add a debug packetwrapper that changes normal clients movement input to be 10 blocks less with a toggleable command to test it.
But I think if in the god mode the player would also not be able to rotate or really hit the other players, so its not that urgent.

**Comment by asofold** [comment]
Hard to tell what's the point here, if the god mode check does not trigger at all.

10 blocks down ... it would block that very implementation, but what with 10.12345 blocksa down .... that's not what we do in NCP :). we don't receive money for blocking one specific implementation of a cheat, and the next day it's bypassed anyway :).

But it'll be interesting what it'll boil down to. Perhaps the god mode thing is related to issue https://github.com/NoCheatPlus/Issues/issues/333 , but perhaps it's another thing.

**Comment by jonesdj1** [comment]
you know you "COULD" you know make your own anti-cheat plugin instead of using a plugin off of spigot have you thought about that then you could most likely use aac with ncp.

**Comment by asofold** [comment]
@jonesdj1 I don't fully understand what you are hinting at :).

@Janmm14 Are botz aac and ncp fight checks activated? If so, it'll certainly be problematic, because statistics and actions/reactions get changed, one plugin will always  receive packets/events after the has, and there isn't always a (feasible) way to account for that. Especially god mode might be pretty sensitive to cancelled pvp/packets and NCP may also cancel some stuff (net checks, fight checks). So perhaps one would need to get an overview of what's activated on either side...

**Comment by Janmm14** [comment]
@asofold He said he activated speed/fly/morepackets on ncp only while aac was handling the rest except movement.
I'll probably try to reproduce this in the next days.

**Comment by asofold** [comment]
Well which NCP checks are activated... both plugins god modes may conflict. I think we might have to take a closer look at what checks are activated...

**Comment by v0idst4r** [comment]
This does not occur in the latest NoCheatPlus, tested on ncp.b0at.xyz.

**Comment by asofold** [comment]
Closing as suprseded - NCP cancels moving events on the latest version of Minecraft and can be configured to do so on legacy versions too (but at a penalty of longer freezing, depending on which backport additions/fixes there may be in the server).
