### ISSUE TITLE
Fullbright

### ISSUE THREAD

**Issue by reded1** [NoCheatPlus/Issues#339]
Hello.
I'd mainly say I play on a factions server. I'm really mad because they just use their FullBright OP hack and they modify the darkness level to 100000!!!! AND WE HAVE TO BUY NIGHT VISION POTIONS FOR DOING THAT. PLEASE PATCH THIS IM FUCKIN MAAD

**Comment by P42C41** [comment]
It's unpatchable

**Comment by jonesdj1** [comment]
yeah please leave thanks

**Comment by asofold** [comment]
@jonesdj1 Don't be hasty.

@reded1 It's indeed not patchable. You could try to detect some things that happen when a player can see everything, but there is no guarantee it'll work, and it'll hardly ever be extremely precise. Typically that's not important enough to program something complicated for.

Technically there are some levers to pull, one could identify actions that are more difficult in darkness and attempt to somehow collect statistics or use abstractions/inputs fit for pattern matching or machine learning.

If i was highly motivated to throw time at all sorts of spots, i'd certainly add something like pattern matching or machine learning, and this could be an interesting test field too, apart from fight checks. Currently it's really not like that.

**Comment by Chnkr** [comment]
reinforced learning would be a great way to automate the detection of fight checks

**Comment by asofold** [comment]
@Chnkr I wouldn't bet my shoes for a general case here, though :). If we don't do something better than detecting outdated cheat implementations (to not focus on entire clients), we'll have wasted considerable amounts of time and probably would keep wasting time. On the other hand, if someone else does the training and ironing out false positives... i could live with adding a little extra bit of infrastructure. With paid+obfuscated plugins those kind of "details" often get lost or become unspoken usually. The idea with NCP is to provide a rather lasting level of protection, anything specific to client-side implementation clearly is secondary (with some gray-zones to consider). 

For fight checks i haven't even implemented the basics of what was planned a while ago, so there is still some ground to cover withwe conventional means. Once everything/most classic grounds are covered, or once there is enough serious developer-wise support, i'll of course consider more methods/paradigms the next moment.

**Comment by v0idst4r** [comment]
No, you shouldn't be mad, and no you don't need a potion to do this in a vanilla client, you can simply download a light overlay and put it over your resource pack.

**Comment by asofold** [comment]
Closing as 'not currently within reach'.

**Comment by Alerithe** [comment]
Just a stupid idea, I saw a concept for something like this, checking the light level of what they're breaking and if (to normal players) it would be deemed 'not visible', then do not let them break it & send some type of message telling them to place a torch/something else to raise its light level.

**Comment by v0idst4r** [comment]
Tons of UHC players use fullbright lightmap overlays as well

On Jan 8, 2017 3:34 PM, "Summer" <notifications@github.com> wrote:

Just a stupid idea, I saw a concept for something like this, checking the
light level of what they're breaking and if (to normal players) it would be
deemed 'not visible', then do not let them break it & send some type of
message telling them to place a torch/something else to raise its light
level.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/NoCheatPlus/Issues/issues/339#issuecomment-271181322>,
or mute the thread

**Comment by asofold** [comment]
@Alerithe Event the client allows to turn up brightness to roughly 'nowhere', so mining in the dark became pretty common. With the DarkTrace plugin i had a statistics about block breaking including light levels, which was so-and-so successful for knowing more.

Indeed the idea to block mining (too many) ores in the dark _and at the same time tell the player_ that this block can not be broken in the dark, could be a simple proactive feature. This does only cover mining and it also has quite some potential to interfere with legitimate gameplay quite a bit.

To really go for it, perhaps a pattern matching / rule based / machine learning based (don't think of catching the cheat only, consider adjusting parameters of rule based checks , using machine learning to some extent) approach could be interesting, in order to find out about when players are acting in the dark in a way they usually shouldn't be able to.

Concerning how they move .... this probably is more difficult than using machine learning with simple inputs to detect fight cheats, because it'll matter what kind of moves you do including which blocks are around and what distances are taken.

So i will not embark on miracling up anything great here - the dark mining thing can and should probably be done as a small extra plugin - only once me or someone else has added more general frameworks for pattern matching / automata / machine learning including how they can trigger violations, how to deal with probabilities and how to notify for such, etc., then side-kick checks for darkness are in range.
