### ISSUE TITLE
Almost Fly Bypass: long jump with queued velocity

### ISSUE THREAD

**Issue by CaptainObvious0** [NoCheatPlus/Issues#374]
#### Short description of the issue.
Players can exploit NoCheatPlus to fly in the air for a short period of time.

#### Complete output of the _ncp version_ command (please prefer text here).
[17:06:59 INFO]: ---- Version information ----
[17:06:59 INFO]: #### Server ####
[17:06:59 INFO]: git-Spigot-6016ac7-10c10b3 ~MC: 1.10~
[17:06:59 INFO]:   detected: 1.10
[17:06:59 INFO]: #### NoCheatPlus ####
[17:06:59 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1057
[17:06:59 INFO]: MCAccess: 1.10-1.10.2 / Spigot-CB-1.10_R1
[17:06:59 INFO]: Features:
[17:06:59 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
[17:06:59 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[17:06:59 INFO]:   defaults: pvpKnockBackVelocity
[17:06:59 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[17:06:59 INFO]: Hooks: AllViolations~NCP~ 1.0
[17:06:59 INFO]: #### Related Plugins ####
[17:06:59 INFO]: ProtocolLib v4.2.0

#### How to reproduce the issue (is it random / always happens / side conditions)?
I used a pressure plate connecting to a dispenser that would repetitively shoot arrows to hit me. After a short period of time, I enabled the cheat LongJump and AirJump and jumped off the platform. I am then able to move a large distance in a very short period of time. More details can be found in the video.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
None

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
None

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.

Video:  https://www.youtube.com/watch?v=0A4qONFRMio&feature=youtu.be

Debug: http://pastebin.com/pMRTGjw4

**Comment by CaptainObvious0** [comment]
Quick Update:

AntiKnockback is not required, it is just easier to replicate. 

This doesn't have to be done with a dispenser with arrows, a player can shoot themselves repeatively with a  bow and arrow and then attempt to fly. This way wont allow farther distance though.

**Comment by asofold** [comment]
Informally that's flight, on  the other hand it looks more like a very long jump, or gliding with a little more descending than you'd expect from gliding. For "real flight" i would expect the cheat being capable of gaining height or staying in-air for an arbitrarily long period of time.

Technically this looks similar to the long jump issue that has been posted before: https://github.com/NoCheatPlus/Issues/issues/365

**Comment by CaptainObvious0** [comment]
The longjump won't work unless you repetitively get hit by arrows. It can still give a player a pretty big advantage. They can spam themselves with arrows and then long jump to an area. I can't find a use to it in normal survival but minigames and factions might have a problem. It requires time to do so I can't find it helpful in PvP.

Anything that I can provide to help with this?

**Comment by jonesdj1** [comment]
tested on a public client it pulls you back after like 10secs in the air and only works if you get hit with like 100 arrows

**Comment by CaptainObvious0** [comment]
It still does give them an advantage. I was able to use only about 6 or 7 arrows with a bow and was able to go a far distance. Depends on your clients settings.

**Comment by asofold** [comment]
Having many velocity entries queued, allows using them within the period of validity (in-order, a couple of seconds).

Currently there is no protection against sparing them up and using them later. Horizontal speed checking also does (for most) not account for the direction, so that helps a little bit too, because horizontal and vertical velocity entries are treated independently and can't invalidate each other, be it by either getting invalidated or by the horizontal entry conflicting with the actual moves.

Estimating latency could help here, but we always have to account for some networking congestion kicking in randomly. Thinkable directions could still be:
* Use multiple inputs for estimating latency (keep alive, using velocity, hitting entities/players, other). This may not make this cheat obvious by itself, but it'll force the client to fake real lag by not sending packets at all.
* Regard the timing and flow of events and velocity use, concerning latency

**Comment by asofold** [comment]
Having many velocity entries queued, allows using them within the period of validity (in-order, a couple of seconds).

Currently there is no protection against sparing them up and using them later. Horizontal speed checking also does (for most) not account for the direction, so that helps a little bit too, because horizontal and vertical velocity entries are treated independently and can't invalidate each other, be it by either getting invalidated or by the horizontal entry conflicting with the actual moves.

Estimating latency could help here, but we always have to account for some networking congestion kicking in randomly. Thinkable directions could still be:
* Regard the timing and flow of moving events and velocity use, concerning how far the original triggers have been apart, and how the distances between using entries are (e.g. number of moving events). If it's only about 4 velocity events needed for the cheat, it'll get difficult to trigger - we probably need to count odd stuff longer term (both short and long term) and deduce stuff - 
* Also keep track of the distance between the positions from receiving velocity and using velocity (spatial distance too), for an extra thing.
* If it's used in factions with multiple players, we could also try to let checks account for the locality, relating to "what others did around there". Perhaps we'll end up with a combination with below points, if we really want to do something here.
* Use multiple inputs for estimating latency (keep alive, using velocity, hitting entities/players, other). This may not make this cheat obvious by itself, but it'll force the client to fake real lag by not sending packets at all.
* Detect special cases and somehow deny effects proactively. This could be combined with other triggers (odd use of velocity, taking distances, -...).
* Perhaps part of the move can be confined somehow, e.g. with reducing exceptions that allow more (danger of new/old false positives though).

**Comment by asofold** [comment]
So to clarify algorithmically:
* In order to have enough velocity entries usable within the set invalidation period (seconds...), they can't use too much time to "collect" velocity entries. How many do they need for which distance? (Jumping over a fence using a bow, can be done with vanilla client, not?)
* We have the entirely legitimate situation, that a player has received 5-20 velocity events, some of which or all of which are just a tiny bit of upwards velocity, all of which  have been created within a comparably short period of real time, and which may arrive at the client in a bunch or with lots of improbable delay between each.
* To use the velocity entries (assuming it's that) for a long jump, you'd need to spread them out, e.g. do so and so many moves with the default gravity (maxed  out with using other workarounds, to use as few as possible gravity), then use one time velocity.
* The spreading out certainly can be detected, e.g. with maintining a counter of moving events and remembering the counter within velocity entries, remembering the counter of the last used entry (and/or last invalidated entry, in case of skipping entries).
* A fast forward detection would be easy, in that you see directly that there have been five or so moves since last velocity use, but the difference of the moving count bewteen the last used and the currently used entry is like 1. One might actually include the server-side tick or even a real time stamp, in order to judge some edge cases.
* Considering false positives, one could make the detection accumulate. Another question is, under which circumstances such a spread could actually be possible (server side lag, every tick an arrow?).
* Despite potentially rare scenarios for false positives, not triggering the first time and/or relating to other edge data could already be sufficiently good, provided we do detect the kind of long jumping curve.
*  (Do consider burning though - here it would be interesting to see, how far can the 'burning vanilla man' jump - this isn't the server side lag case, but interesting to see how debug logs and distances taken differ).

Another question is to measure time ... could think of a triple like (real time, server tick, moving event count +- equivalent), could make this a generic thing to be fetched from PlayerData some time (then thread-safe, disregarding exact order).

**Comment by jonesdj1** [comment]
I think the hacc bhop speed fix patched this

**Comment by asofold** [comment]
Closing as partly fixed/postponed. It'll be in the Closed items project view.
