### ISSUE TITLE
Crazy passable VL, lagbacks, players stuck on blocks

### ISSUE THREAD

**Issue by L4BORG** [NoCheatPlus/Issues#404]
#### Short description of the issue.
Sometimes, randomly, usually when TPing but not always, player would get stuck on block (usually slab or stairs) and won't be able to move until they get kicked for too many packets. Disabling passable fixed this, but that's prob. bad idea, before that I also tried blockchangeonly but it didn't help.

#### Complete output of the _ncp version_ command (please prefer text here).
```
>ncp version
[13:09:34 INFO]: ---- Version information ----
[13:09:34 INFO]: #### Server ####
[13:09:34 INFO]: git-TacoSpigot-"65fd35f" ~MC: 1.8.8~
[13:09:34 INFO]:   detected: 1.8.8
[13:09:34 INFO]: #### NoCheatPlus ####
[13:09:34 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1072
[13:09:34 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[13:09:34 INFO]: Features:
[13:09:34 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[13:09:34 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[13:09:34 INFO]:   defaults: pvpKnockBackVelocity
[13:09:34 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[13:09:34 INFO]: #### Related Plugins ####
[13:09:34 INFO]: ProtocolLib v3.6.5
```
#### How to reproduce the issue (is it random / always happens / side conditions)?
Using a command that would TP player or sometimes just by jumping around.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
Tried messing around with blockchangeonly but it didn't work.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
ViaVersion.

#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
```
>ncp info L4BORG
[13:13:51 INFO]: NCP: Displaying L4BORG's violations...
[13:13:51 INFO]: NCP: [13:06:30] player.survivalfly VL 48  (n3a16m19)
[13:13:51 INFO]: NCP: [13:13:51] player.passable VL 368  (n368a1m1)
```

Is there any other way to make passable check less strict?

**Comment by L4BORG** [comment]
Also the same issue is not present on the same setup with old NCP

```>ncp version
[13:16:37 INFO]: ---- Version information ----
[13:16:37 INFO]: #### Server ####
[13:16:37 INFO]: git-TacoSpigot-"65fd35f" ~MC: 1.8.8~
[13:16:37 INFO]:   detected: 1.8.8
[13:16:37 INFO]: #### NoCheatPlus ####
[13:16:37 INFO]: Plugin: 3.15.0-SNAPSHOT-sMD5NET-b1060
[13:16:37 INFO]: MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
[13:16:37 INFO]: Features:
[13:16:37 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
[13:16:37 INFO]:   checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
[13:16:37 INFO]:   defaults: pvpKnockBackVelocity
[13:16:37 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | CatchAllAdapter
[13:16:37 INFO]: #### Related Plugins ####
[13:16:37 INFO]: ProtocolLib v3.6.5```

**Comment by asofold** [comment]
We should distinguish issues a little bit - recent tickets are very similar, and likely have the same cause(s).

I see three issues:
* Lag/freezing. To be expected to happen slightly more than before - once a set backl by NCP happens, all moves get cancelled hard until the (now scheduled) teleport to the set back location happens. Previously the teleport would have happend before any other incoming packets would've been processed. Thus previously there had been a chance that the player could've moved on legit, due to small distances taken or horizontal buffer or what not. The actual issue could also be some data resetting/overriding thing, with the gap between cancelling the move and teleporting to the set back location.
* Getting kicked for morepackets. This indicates that the server side teleporting (like moved wrongly and correcting players outside of blocks) and the NCP set back conflict after recent changes.
* Passable violations !? Typically i would expect these to become less, because the moves until set back just get cancelled directly, with no checks running until the set back has happened. Still the timing can be intricate with the new gap, and i could imagine something like a set-back loop (without vanilla server "moved wrongly" and the like), where the player keeps moving, and for some reason leaving the gap towards the teleport happens, "always" or at least too often leads to cancelling the first move the player does, starting at the set back location - thus the first non-cancelled move that NCP is processing would be the second move after moving off the set back location, due to latency, leading to NCP assuming that move to be too big, thus setting back again, and so on.

For fixing this with the current implentation, a _debug log_ (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) , better several logs, would be the fastest way out of trouble (other than reverting to build 1066). I'll also attempt to reproduce stuff with a remote server / adding some latency + tools for types of delayed teleport while moving and so on.

(Technical details/directions: https://gist.github.com/asofold/227dc7c43f769d05bae2a52924062cb7)

**Comment by L4BORG** [comment]
Ok, so I did:

- /warp loc
- move around a bit...
- /spawn ... and got glitched
after that I could move my player or view for like a minute or 2 and then I suddenly stopped glitching (even tho I didn't touch mouse or keyboard)

npc debug log: http://static23.us.to/files/l4borg.txt

**Comment by asofold** [comment]
Thank you very much, that log is quite telling.

Build 1073 contains alterations, which should reduce some of the extra cancelling ("Cancel move, due to a scheduled teleport (set back)."). With a little luck, this is as good if not better than build 1066. But ok ... perhapos shouldn't write such in a  bug report.

**Comment by Xayanix** [comment]
I can confirm, this issue is real.
I just wanted to post same problem here.

**Comment by asofold** [comment]
@Xayanix Did you test with build 1073? Could you state details about other side conditions (ViaVersion, other plugins with moving / position correction / teleport optimization, about the same spigot version)?

**Comment by Xayanix** [comment]
No i did not try 1073, just downloading it right now.
ViaVersion - no
Other plugins - yes, custom anticheat created by me, but its not doing it
Spigot: 1.7.10

How it looks like: https://www.youtube.com/watch?v=py3l4wbY6iA&feature=youtu.be
I will test if 1073 build works.

**Comment by L4BORG** [comment]
b1073 seems better there are still some lagbacks when moving back and forth between 2 slabs

http://static23.us.to/files/l4borg2.png

http://static23.us.to/files/l4borg2.txt

and occasionally when jumping, or maybe VL would build up and lagback player?

**Comment by Xayanix** [comment]
It's better on 1073.

**Comment by L4BORG** [comment]
Here's another one: http://static23.us.to/files/l4borg3.txt

trying to sprint past slab (almost cutting corners - from ground and from another slab)

**Comment by asofold** [comment]
* Are any add-ons for NCP in use? Anything that relies on set back handling and alters it (!) might conflict.

I'll dig into the log(s) and make a couple of other attempts.

**Comment by L4BORG** [comment]
We're not using anything like that, but I did I forget to mention that we're using latest BungeeCord (and latest ViaVersion, ViaVersion is running on Spigot instances, not bungee).

**Comment by asofold** [comment]
@Xayanix Which version of spigot are you using (pls the related output from 'ncp version' ? Could also use info on add-ons and ViaVersion (or equivalent, if in use).

**Comment by Xayanix** [comment]
- Server version: http://scr.hu/0duk/drvs7
- No, everything was fine until updated from older build to b1072
- Yes, i am using bungee.

On 1074 its better, but it is not perfect.

**Comment by asofold** [comment]
If you updated from a much older build than 1066, of course there could be other changes that relate to survivalfly. Changes between build 1066 and 'latest' are what i am most concernerned right now (potential of freezing, thinkable set-back-loops, such).

**Comment by Xayanix** [comment]
Ok, i have another question, non related to this issue.
Can you add possibility to set action after detecting SurvivalFly?

I want to teleport player to the first block under him (to ground) instead of teleporting back.

**Comment by MarkElf** [comment]
>I want to teleport player to the first block under him (to ground) instead of teleporting back.

Plugins on Spigot such as ntac and pncp offer a "drag down" hook which drags players down rather than teleporting them back.

**Comment by L4BORG** [comment]
I was testing b#1074 and it's much better now. Maybe some minor glitching with slabs every now and then (rarely, nothing compared to previous version and considering viaversion) but I can't replicate it so far, could aswell be lag. I'm testing it now on a server with real players.

**Comment by asofold** [comment]
@Xayanix @MarkElf Do note, that with the new set back handling (1067 +), exactly these plugins might conflict :p, depending on how they're doing stuff (not confirmed, but might in theory).

I'll certainly tackle this topic more or less soon, either i'll build options into NCP directly or i'll provide API for other plugins to adjust the set back location more easily.

I'm currently aiming at the force-fall type of adjustment, rather than ground below, but it could also become that - first i have to stablize current changes (how to set back at all technically, independently of the set back location).

@L4BORG Thank you for testing. Another recent ticket (survivalfly...) indicates, that there could be some side effect or unintended code change, which increased false positives from build 1067 on - hard to believe, as (supposedly) nothing related to false positives got changed since, but never know (if the set back location should get set differently, it can be of relevance, e.g. with height differences).

**Comment by L4BORG** [comment]
SurvivalFly is mostly an issue with laggy players, from what I saw so far.

**Comment by L4BORG** [comment]
http://static23.us.to/files/l4borg4.txt

just springing and jumping around with random lagbacks every now and then, it looks like now survivalfly is coming up, that's with 40ms ping, players with 150+ or 250+ would get more lagbacks...

**Comment by asofold** [comment]
Build 1076 is a little more bleeding edge, because it contains rather more internal changes (slight potential for bugs). It does also contains a fix for leniency with scheduled teleporting, possibly not of practical relevance.

So the most consolidated thing probably is build 1075 (without arrow-chair-compat it'd be build 1074, who knows if there'll be an arrow-chair-tp exploit :) ...).

Concerning 'more lag backs', it stays a slighty peculiar topic, thinkable:
* Bugs.
* Laggy players (not just ping), might have packets cancelled out,  if too many arrive. So the resulting move with the next accepted packet will cover a larger distance, potentially. This could lead to a set back.
* For higher ping players, a false positive that also would happen for low ping players, will have more impact, because there are more incoming packets going to be handled, before the client even know there's a position correction. Thus the impact is heavier, and this causes the impression of 'more lag backs'.

250 ping isn't that high though, it'd be nice not to have too much trouble with that.

At some point i'll certainly go back to working around false positives and/or adjusting the modeling. After all we do have interesting infrastructure built in, in order to efficiently work around stuff, without causing too much of exploitability. Only it needs the ability (and time) to reproduce/confirm or at least to have one or several debug logs of pretty much exactly that type of issue, so one could add a "blind workaround".

**Comment by asofold** [comment]
The actions entries for survivalfly and creativefly have been faulty since build 1067. Build 1080 contains a fix for that. Alternatively you could use build 1075 and manually correct the actions ('cancelvl' should be 'cancel vl').

**Comment by L4BORG** [comment]
b#1081, sprinting back and forth (not on slabs but close to slabs):

http://static23.us.to/files/slabs.png

would still trigger passable:

```

>ncp info L4BORG
[13:09:35 INFO]: NCP: Displaying L4BORG's violations...
[13:09:35 INFO]: NCP: [13:05:14] player.passable VL 1  (n1a1m1)
```

http://static23.us.to/files/slabs.txt (I've managed to get VL at the end of log)

**Comment by L4BORG** [comment]
Stuck on cobblestone wall, passable/survivalfly false positives:

```
>ncp info L4BORG
[13:25:11 INFO]: NCP: Displaying L4BORG's violations...
[13:25:11 INFO]: NCP: [13:21:55] blockinteract.direction VL 0  (n2a0m0)
[13:25:11 INFO]: NCP: [13:22:28] player.nofall VL 1  (n1a1m1)
[13:25:11 INFO]: NCP: [13:23:19] player.passable VL 11  (n11a1m1)
[13:25:11 INFO]: NCP: [13:25:03] player.survivalfly VL 458  (n71a6m8)
```

http://static23.us.to/files/cswall1.png
http://static23.us.to/files/cswall2.png

http://static23.us.to/files/cswall.txt

that nofall is from falling into void (I tped out before dying)

**Comment by Xayanix** [comment]
b1078, i will check if its same on newest one
https://www.youtube.com/watch?v=4ajIHwgEYNA

**Comment by Xayanix** [comment]
Im my opinion its working fine on b1082.

**Comment by asofold** [comment]
@L4BORG  If i judge right this is now about checking out the false positives in general - getting stuck (passable) too long doesn't happen anymore? Im missing checking out the logs you posted, because i was digging up other stuff, but i'll very soon have a look.

**Comment by L4BORG** [comment]
Well I was testing this with b1081 and from what I saw b1082 didn't really change much.

**Comment by asofold** [comment]
@L4BORG Yes certainly, what i should ask is: Does 'players stuck on blocks' or  'Crazy passable VL' still happen? I'll certainly have a look at the logs provided, later today, but couldn't do more than save to disk so far...

**Comment by L4BORG** [comment]
Oh that, yeah b1080+ fixed that.

**Comment by Xayanix** [comment]
My players still do report these bugging in blocks like there: https://www.youtube.com/watch?v=NMP7AfOANZQ&feature=youtu.be

**Comment by asofold** [comment]
@Xayanix I'll clarify what i see: Seems shortly set back in/on stairs? Hard to see what exactly happens, only watched 2-3 times though.

This could also be Minecraft itself, could only be distinguished by being able to assign check failures (passable, and perhaps flyingfrequency, morepackets, possible the fly checks) , or by debug logging such. At least with riding horses Minecraft would set you back countless times on longer stairs. (My local test server always has pyramids of kinds of blocks, including layered snow pyramid and randomly put layered snow - i'm still not the best at reproducing reported issues, unless really idiot-proof.).

**Comment by Xayanix** [comment]
Just join my server and try playing for 10 minutes.
I can debug your name.

**Comment by asofold** [comment]
Can't this be done in text (passable violation on stairs), something like that?

I'm currently not able to hop on servers (perhaps @MyPictures could? :) ) ..

**Comment by asofold** [comment]
It's a little bit difficult to judge: 
* Are we just dealing with false positives (and since when are they happening more often than now, or are they not happening more often but still are annoying)?
* Are we dealing with increased trouble due to more freezing in case of A) a set back by NCP B) the server adjusting the location of a player (!) - So this could also be indirectly following from handling things differently now.
* (Both?)

It could be that we can reduce false positives stair-like setups (half steps, stairs, full blocks...) false positives with an extra check that also existed before: run the xz axis/axes(?) first and then y - this might do something (just had an fp on 1.11.2 on top of a full block glowstone thing).
* Typically only on moving down.
* Only moves with rather small distances (h(v)? This would be interesting to know.
* Perhaps the vertical move can only be very small (roughly gravity)?

Maybe that should be tested... it would appear in the debug log. A strategy to find out how helpful this is, while avoiding endless testing sessions with few players, would be to add debug tokens to the configuration, for which debug logging for certain entries is always done for all players, ignoring the check.debug flag. For a release those could be removed, but this could give some more leverage on rare issues (Think of an entry like 'moving.passable.alternate_axes' in a list somewhere around logging.extended.debugalways).

**Comment by Xayanix** [comment]
Just updated to b1091 and now it's awful!
Everyone is getting stuck every 5 minutes, a lot of false positives.

**Comment by asofold** [comment]
@Xayanix We have to distinguish again....
* Which checks trigger?
* Do they trigger more often than before?
* Do players get frozen longer than before?
* Have you updated other plugins that might be related as well (other anti cheating / extensions)? It would also be interesting to know if you're running such at all at present.

Unless i am overlooking something, the most significant changes have been:
* For Minecraft versions since roughly 1.9 that have the 'confirm teleport' packet: NCP cancels out moves on packet level, until a teleport is verified. -> this has the potential to freeze players a little more than before, despite potentially preventing other types of more severe false positives.
* The morepackets check has now a standard set back age of 40 moves (roughly 2 seconds in theory). This would set the players further back, in case of false positives for morepackets.

Otherwise passable hasn't really changed, i'll address false positives there soon.

**Comment by L4BORG** [comment]
So far it looks fine on 1.8.8 (latest TacoSpigot, ViaVersion and NCP b#1091

**Comment by asofold** [comment]
Added alternate order of axes checking to passable with 1098. Options to do without ray (actually axis-) -tracing have been removed, as they only pose risks and don't really address what was meant to be addressed anymore, because the undrlying implementation has changed.

So I'll now close as fixed, in favor of new issues with more confined side conditions. Some false positives with survivalfly will still get addressed (elytra likely too). Poke me if i have overlooked any information in this thread, or better open a new issue linking it, if relevant.
