### ISSUE TITLE
NoCheatPlus setBack player move event problem!

### ISSUE THREAD

**Issue by craftrise** [NoCheatPlus/Issues#406]

**Comment by asofold** [comment]
Build 1073 isn't good to stay on:
* You probably should use build 1075 (1074 is ok too), because those have been tested and have with the actually relevant changes inside, or the really bleeding 

You are running AAC in parallel? Have you ensured to disable conflicting checks on either side? Especially moving related checks should only be run on one side.  This needs to be checked first.

Technically another plugin (or custom server modification) is conflicting here

**Comment by HaqGamer** [comment]
Hi I just wanna add something, the checks seem to work but it doesn't set the player back when he flags like he used to.

**Comment by asofold** [comment]
@HaqGamer I don't know which build of NCP you're using and which version of which variant of Craftbukkit/Spigot ... so i can't say much more than that that's what i have just changed. Are you indicating, that the new set-back handling can be exploited ? I'd expect slightly longer moments of freezing for sure, which could also be what you're telling.

I've come across an oddity on a local test server, that i can't fully explain (ProtocolLib needed). The on-tick teleporting thing may skip the teleport, if the player is already there, or if the client has sent confirmation about being/going there. The latter has potential for absue and i did encounter it on a simple local test server (spigot 1.11.2, NCP build 1076 or later): skipping due to packet level confirmation shouldn't really happen, because

**Comment by HaqGamer** [comment]
Hi I am using b1077 with the default config on Spigot 1.8.8.

**Comment by asofold** [comment]
@HaqGamer Thank you - so you're saying the set back is done differently now ? Or you are saying it leaves potential for cheats?

**Comment by HaqGamer** [comment]
I am trying to say that b1077 doesn't setback the player if they use something like longjump, flight, etc...

**Comment by asofold** [comment]
@HaqGamer Does it change with build 1078 (on MC 1.8.8) ? Have you (by chance) tested things with MC 1.9 or later?

**Comment by HaqGamer** [comment]
Ok, it seems to work.

**Comment by asofold** [comment]
Thank you for checking out things :) - did you happen to test the same type of thing with 1.11.2 as well, just in case?

**Comment by HaqGamer** [comment]
No I haven't tested on 1.11.2 yet, since my server is 1.8.8 I never bothered.

**Comment by asofold** [comment]
ok, thank you for testing, still.

**Comment by craftrise** [comment]
This problem not fixed (The player always throws it back when he walks. --> last build 1078).

**Comment by asofold** [comment]
@craftrise I have to repeat, because we need to clarify these things:

You are running AAC in parallel? Have you ensured to disable conflicting checks on either side? Especially moving related checks should only be run on one side - never have two plugins potentially set back players, unles they're explicitly crafted for each other. This needs to be checked first. Please check for conflicting configuration (moving/flying/speeding, possibly flying packets too).

**Comment by craftrise** [comment]
You are running AAC in parallel? -> Yes
Have you ensured to disable conflicting checks on either side?  -> Yes

**Comment by asofold** [comment]
@craftrise

* Are you sure, none of your plugins alters moving (make players slower or faster by default, extra anti cheating for moving?
* Otherwise we'd need to check with build 1079 - if that doesn't help, the only thing that'll help will be debug logging a player who has that isssue. An ordinary violation log for build 1079 would also be good, but if that does'nt show anything new, only a debug log can help.

**Comment by asofold** [comment]
The actions entries for survivalfly and creativefly have been faulty since build 1067. Build 1080 contains a fix for that. Alternatively you could use build 1075 and manually correct the actions ('cancelvl' should be 'cancel vl').

Not sure that touches this issue, but it'd make sense to test with corrected actions entries rather.

**Comment by asofold** [comment]
Await other issues with 1090 :=).
