### ISSUE TITLE
timings pct tick high

### ISSUE THREAD

**Issue by Max633** [NoCheatPlus/Issues#412]
Hi

![ncp](https://cloud.githubusercontent.com/assets/7448800/25056969/a0e88ade-216c-11e7-874b-3f190bfe26be.PNG)

It's normal? :o 

Thanks

**Comment by asofold** [comment]
Hi, i assume this is about the postEnable task, as the other events need more events to be telling enough.

The post enable task runs once after enabling of the server, so this shouldn't pose a threat to your server, other than delaying startup by that amount.

This appears to be some kind of an issue, because the amount shown there seems to be a lot, it doesn't seem to be the typical duration. The task is mainly doing some command registration and permissions registration stuff, which is done there, in order to be sure all plugins are enabled when it's done.

This could indicate that the delay is due to altering/creating permissions within NCP during postEnable. There has been past versions of CraftBukkit/Spigot which had one permissible object (updating with permissions changes) per command block - if there were command blocks loaded e.g. near spawn - so altering a  good lot of permissions would keep updating each of the command blocks permissions. This had been fixed in later versions of Spigot.

So the output of the 'ncp version' command also might indicate something (craftbukkit/spigot version?). This also could depend on the permission plugin (possibly other plugins) so those _including versions_ could be an interesting information as well.

After all if this is just about postEnable running once, so it also could be ignored, unless it's a problem with 2 seconds startup delay.

**Comment by asofold** [comment]
Assume resolved - one time event.
