### ISSUE TITLE
Question: Water walk and Jesus - context

### ISSUE THREAD

**Issue by IManthe** [NoCheatPlus/Issues#416]
I just wanted to know what check would be used to stop people from using Jesus(water walk) and at what version or NoCheatPlus it was added at.

**Comment by asofold** [comment]
There has been a water walk check since ages - however ever since it's been largely non-functional against any cheat implementation that is more sophisticated than 'entirely simple and straight forward'. 

So let's admit - water walk / dolphin is simply not detected.

_However_ there has been an addition to monitor/confine the speed within water (+air) medium - which i would rate more important than detecting the cosmetic 'is walking on water', provided it really works.

So the speeding part should be limited (somewhat). To just detect and possibly ban the mere use of not having to simulate swimming, ... that'll be done later when the really important stuff is done.

If you're concerned - AND happen to be able to test a cheat client - to things can be very interesting, if not of great help (independently of each other) - it does need using the latest release of NCP for reference:
1. Use 'ncp stopwatch distance 50' to measure 50 blocks distance swimming with the cheat. Best keep time between command and swim/cheat as short as possible, best using the repeat command feature - you cna repeatedly use it and it'll stop the stopwatch after the set distance, roughly. Preferable would also be a run without cheat on, but i can do comparison without cheat on, if needed. This doesn'T expose the exact technique of a cheat, for the case someone trusts you not to expose stuff. This woul
2.  If you are in full control of both server and cheat client, and don't have the developer/owner trust you to not give away details, a debug log of cheating (no need for not cheating :) ) would be helpful for creating a fix later on (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players).

Still 1. is most important, because it'll reveal what they can do with the latest version of NCP.

**Comment by asofold** [comment]
Assume resolved.
