### ISSUE TITLE
BlockChangeTracker is not working! Bugging back

### ISSUE THREAD

**Issue by scorixear** [NoCheatPlus/Issues#425]
#### Short description of the issue.
I wrote a while ago a request, if there can be a method implemented, to check, if a certain player stands on a FalseBlock (by packet sending). So that they can walk on them without  bugging back.
Well, they are bugging, if the blockchange is removed and they should fall down (I also removed the block with ncp of course)
#### How to reproduce the issue (is it random / always happens / side conditions)?
I use this in my MoveEventListener:
`
public class MoveListener implements Listener {

    private BlockCache.BlockCacheNode node;
    private BlockChangeTracker bct;

    public MoveListener()
    {

        //noinspection deprecation
        node= new BlockCache.BlockCacheNode(Material.STAINED_GLASS.getId());
        node.setBounds(new double[]{0.0,0.0,0.0,1.0,1.0,1.0});
        node.setData(0);
        bct = NCPAPIProvider.getNoCheatPlusAPI().getBlockChangeTracker();
     }
    @EventHandler
    public void onMove(PlayerMoveEvent e) {
           Location l = e.getTo();
           setArea(-1, -1, l, e.getPlayer());
    }
    private void setArea(int x, int z, Location start, Player p) {
        UUID world = start.getWorld().getUID();
        int ticks = TickTask.getTick();
        long changeid= bct.getNewChangeId(ticks,false);

        if (p.getLocation().getPitch()>82) {
            setAir("start", 0, 0, start, 4, world, changeid, ticks);
       } else {
            setBlocks("start", 0, 0, start, 4, world, changeid, ticks);
      }
    }
    private void setBlocks(String s, int x, int z, Location start, int data, UUID world, long changeid, int ticks) {                                             
        Location left = new Location(start.getWorld(), start.getBlockX() + x, start.getBlockY() - 1, start.getBlockZ() + z);
        Material block = left.getBlock().getType();
        if (block == Material.AIR) {
            bct.addBlockChange(changeid, ticks, world, left.getBlockX(), left.getBlockY(), left.getBlockZ(), BlockChangeTracker.Direction.NONE, node);
            changeBlocks(left, Material.STAINED_GLASS, data);
            removeBlock(left);

        }
     }
     private void setAir(String s, int x, int z, Location start, int data, UUID world, long changeid, int ticks) {                                                
        Location left = new Location(start.getWorld(), start.getBlockX() + x, start.getBlockY() - 1, start.getBlockZ() + z);
        bct.removeAllEntries(world, left.getBlockX(), left.getBlockY(), left.getBlockZ());
        if (left.getBlock().getType() == Material.AIR)
        {
            changeBlocks(left, Material.AIR, 0);

        }
        Location right = new Location(start.getWorld(), start.getBlockX() + x, start.getBlockY() - 3, start.getBlockZ() + z);
        Material block = right.getBlock().getType();
        if (block == Material.AIR) {
            bct.addBlockChange(changeid, ticks, world, left.getBlockX(), left.getBlockY(), left.getBlockZ(), BlockChangeTracker.Direction.NONE, node);
            changeBlocks(right, Material.STAINED_GLASS, data);
            removeBlock(right);
        }
     }
    private void removeBlock(Location remove) {
        Bukkit.getScheduler().scheduleSyncDelayedTask(Nyanfighters.getInstance(), () -> changeBlocksReal(remove, Material.AIR, 0), 20 * 2);
    }
    private void changeBlocks(Location l, Material m, int data)
    {
        for(Player p: Bukkit.getOnlinePlayers())
        {

           if(p.getLocation().toVector().subtract(l.toVector()).length()<25)
           {
               if(YmlMethods.isInArea(p.getLocation()))
               {
                   WrapperPlayServerBlockChange w= new WrapperPlayServerBlockChange();
                   w.setLocation(new BlockPosition(l.toVector()));
                   w.setBlockData(WrappedBlockData.createData(m, data));
                   w.sendPacket(p);
               }
           }
        }
    }
 }
`
#### Have you made any (noteworthy) changes to the default configuration of NCP?
No
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
A own programmed Plugin named NyanFighters (Code provided above)
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
I can attach a debug of a player, teleporting back, but I see no real reason, because the reason is obvious.
NCP thinks, the player is bugging through a block, but the blockChange is already removed

**Comment by asofold** [comment]
A debug log or at least an allviolation logs stating checks and tags would be very good, unless it's obvious in terms of the code only removing the latest block change entry instead of all  (right now i am sure).

In general the passable check should not be able to trigger at all, for positions that have past block changes (it's not even evaluating further than 'something happened there in the past', at present), so i assum it could've been the survivalfly check, in which case a debug log will tell something, e.g. it could be due to the player moving as if the block still was there.

In fact if you send the player the air change and remove the block on server side, you'll still have to deal with incoming moves, resulting from the client not yet knowing the map has changed, due to latency. If this turns out to be the issue ... perhaps i'll have to add another twist (if necessary), so your method should be changed to a) remove all entries for that block b) add a faster expiring entry for that block, to ensure some latency is ok .

Another thing could be to send an extra keep alive packet and once receiving the answer ensure to hard-remove all entries for that block - if that's appropriate at that point of time, also considering entries possibly getting re-added. So there more bookkeeping would be necessary.

Not sure what will be the best solution, keeping track of change ids and selectively removing those or allowing to update max-validity time or something like that. Remains to be seen, why exactly this happens - will have a closer look at the report + code a little later.

**Comment by scorixear** [comment]
Ok, you will do what you can do 👍 
here is the log of ScorixEar, who is bugging https://pastebin.com/uq3Hypyf

**Comment by asofold** [comment]
The log is a little bit odd - it's very short, directly after player join (indicating at a potential bug or cross-plugin thing), and it only shows fall damage being dealt. It would be best to have several tries in the log to get varying perspectives on the issues(s).

_In adjust NCP set backs via a plugin, i strongly suggest using MovingData.setTeleported() and not cancel violation processing, neither teleporting the player actively nor use PlayerMoveEvent.setTo yourself. This only goes for the latest builds of NCP around 1088._

**Comment by scorixear** [comment]
https://pastebin.com/M1EsTeCL
It is continuing like that

**Comment by asofold** [comment]
Could you include in the debug log when you remove blocks, just for testing?

You could guard it by MovingData.debug, or just temporarily add something like:
NCPAPIProvider.getNoCheatPlusAPI().getLogManager().debug(Streams.TRACE, "removed blocks: " + ...); (Might use StringUtil.join, or LocUtil.simpleFormat+-block, if convenient).

My assumption is it's about latency rather, but it'd be good to have the sequence of things in a log.

**Comment by scorixear** [comment]
Hi, i want tot try NC NCPAPIProvider.getNoCheatPlusAPI().getLogManager().debug() but there is noch Streams.TRACE, only Streams.TRACE_FILE
And where gets the debug than written

**Comment by scorixear** [comment]
nevermind, found it:
https://pastebin.com/xjGzdK0e

**Comment by asofold** [comment]
I wasn't sure myself and intended to look it up ... got distracted.

Looks good, i'll interpret somehow today/tomorrow. It'd be even better with x Y and z coordinates for blocks :). But it looks like this suffices.

So far quick glance:
* If you remove blocks from the block change tracker at the same time yo usend the block change, there _will_ certainly be latency issues - the player will keep moving as if the blocks were there at least until the "removed blocks" arrive at the client side (server->client time). This will need some concept to deal with, not sure whats best right now, perhaps an estimation/setting to set maximum allowed time for a block change entry to.
* There may be other edge cases, where the fake blocks haven't been removed, but the player is triggering some workaround, which doesn't check for past states (there are many workarounds, like a shorter move due to touching ground ground). This could get complicated.

**Comment by scorixear** [comment]
Now I got confused, are you talking about the blockchanges in ncp or the real block changes by spigot?
The blocks are removed, when the player is looking down, so he will fall down.
If point one means, that the ncp block will be removed bevor the blockchanges, i don't see a problem.
The player wont realize, that he is bugging around because he still sees other block under him.
And he is looking down to intend to get down. NCP is teleporting him back to his position until the spigot block changes arrived and the client side also falls down (now there should be no bug).
But if it is switched it will be a problem. Maybe I just set the Block 20ms later after the block change of ncp
or you can reduce the latency :)

**Comment by asofold** [comment]
Oh what i am refereing to is roughly like:

1a) remove blocks server side -> 1b) so and so milliseconds travel time until the client notices -> 1c) the packets have arrived at the client.

2a) The player is moving on the fake blocks 2b) the player is still moving on the fake blockjs 3c) the player notices, because block changes have arrived.

(The player can look down AND still move ... resulting in a time of freezing. As long as the player keeps moving on the blocks that already have been removed server side, the server will certainly set them back with each arriving moving packet, resulting in a longer freezing period.)

So the point is that the client still sends moving packets while you already have removed the blocks server side. So there will still be packets coming in until the client has actually received the changes - 20 ms is very few, on real servers you may have people with 250 ms ping (128 ms till there) and even much higher, depending on what your plugins/server-type make 'playable'.

Not sure i understood right what you mean with bugging though - just freezing in-air longer?

**Comment by scorixear** [comment]
Ah, so you mean the block changes of Spigot, got it.
I mean with bugging through, that The client sees the Blocks getting removed (1c is done) and falls down, but ncp is teleporting the client back to his start position, and after maybe 400 to 600ms ncp lets the player fall down a bit until he gets teleported for 400 to 600ms back to his new start position. The bugging means, that from client site, he should fall down, but he is not allowed to fall down, because ncp still thinks, that there is a block
And I don't want that xD thats why i thought I remove npc blocks early, wait for a bit and than actually change the real block changes

**Comment by scorixear** [comment]
I added a latency on my serverside change of blocks, so that ncp will remove the blocks and than after 3 ticks (i think 300 ms) the block change will be sent to the clients.
It didn't do anything... Still bugging up like hell

**Comment by asofold** [comment]
Isn't that the wrong way round? And 3 ticks is 150 milliseconds :).

In general:
1. Send the block change (set to air) to the client.
2. After the (maximally) assumed duation that the packet needs to get to the client blocks may expire or get removed.

If you first remove the blocks and then tell the client, it will bug for sure - perhaps it's been a typo or just everybody is confused. If this doesn't help i'll make a drawing :) with function call examples - after ensuring we have that we can do a new debug log...

**Comment by scorixear** [comment]
Jesus, so I am stupid as hell.
With your suggestion it worked. There is a problem, that the server cant set the blocks fast enough when the player falls but that is none of you problem anymore.
Thank you ^^

**Comment by asofold** [comment]
Not stupid - it quickly happens to mix up the symmetries :p, i've not been 100% precise either.

I'm not 100% sure what you want to do in terms of 'fast enough'.
* Setting a too small area so players drop down when they walk blindly? That's classic like with lilypad-flying-carpet thing. Can't do that much more than to fill a larger area, keeping it confined by estimating where the player is moving. <- Rather not this?
* The players are intended to fall, but you want to place another level underneath, letting it pop up when the player is falling. This would be very difficult, with networking congestion or lag on either side, it can easily happen that there is a rough second where the player is moving as if not having received newly put blocks... If it's about a level below, you could though, within some time frame test if the player falls below the intended level and teleport them back up (cheating but perhaps it's helping the game).
* In general if it's some kind of game type - you could try to detect when players are falling without need and just give them like 2 (+-) times per game that they get teleported back for free. That's potentially complicated to do as well, perhaps.

That's just brainstorming/assumptions.

**Comment by scorixear** [comment]
Yeah, I already implemented number two.
It works, kind of, the problem is more, that how to detect if a player is falling to fast and doesn't get pushed by a velocity from a implemented special item.
The point is, there has to be this layer set underneath the player when he is falling. It stops the player to fall to fast and fall past the set blocks when he intendd to stop falling. So I need this slow down and this slow down is sometime very bad. Every block setting is bad when I think about it.
With a ping of 200ms an more, the game is nearly unplayable

**Comment by asofold** [comment]
Have you considered to set an invisible type underneath anyway? You could replace it by something real once appropriate - or you even only need to update the entries normally, but vary what you send to the client.

So the layer already is in place before the client falls - this may not be doable, if multiple players are on multiple levels though. (It also allows cheaters to see the blocks ~ but it's a game principle anyway. Problem remains if the invisible blocks _are or can be_ in the way of others.)

----

Another try could be to send a little velocity with setting the blocks underneath to air, this might give you the needed delay, you could also send velocity another time a little later. This isn't 100% secure and all, but it could give the necessary time - vertical velocity is used as the new speed, so it's not necessarily added to the speed or something - and NCP needs to know, otherwise it might trigger, if you only use packets. 

----

_Similarly but with another twist_ could be sending relative teleport packets - ncp can't judge these so there could be issues with velocity and the net checks, but they teleport relative to the position (hearsay, be careful :9) - using multiple ones of these could allow smoothen the fall, sending every tick or every n ticks for a second beginning with setting blocks to air, possibly 1-3 packets suffice. NCP still needs to know somehow, so you might have to add velocity entries to NCP too (MovingData / vertical velocity) - you could try the smoothening with being exempted from ncp first and then start to tackle issues with NCP.

----

Other topic: if you want to know about velocity (in-air) there could be the option to check out what data NCP has set. There is MovingData.isVelocityJumpPhase() which only states something like "something similar to velocity happened since taking off", and there is the vertical velocity tracking (queued velocity entries (and unsued, not sure that helps though)). The other thing is the past move tracking of NCP, which tracks actually used velocity too, but it only covers 3 moves by default - if you need a plugin to check, and are able to compile NCP yourself you could set the number of stored moves to 40 or what not (1 is one client side tick usually). Could also be made configurable  (hidden setting perhaps). <- Or you listen to velocity events (..).

So far for another round of fast-forward...

**Comment by scorixear** [comment]
I personally like you second suggestion with setting the vertical velocity. I think I understood, that I will set the fallspeed with that (otherwise I would just do a short math calculation and give the player a velocity upwards according to this fallspeed).
I will try that (and I can remove the blocksetting in that way).
You will hear from me soon

**Comment by asofold** [comment]
Yes, it would also set an upwards speed if you set so (positive y), and it's not much interrupting, because it's not setting them back (the rocket boots flying plugin used velocity too long time ago, so did i on my server + lilypads for hovering, until the creative-like flying was added). Using player.setVelocity (don't bother about getVelocity or adding) will probably be the simplest and fastest - NCP will receive a velocity event, however it will likely fire directly, and that means nested if done from within ordinary event handling, just to have noted so. NCP doesn't do much with a PlayerVelocityEvent, so it might simply work.

Just to add it once more: Players can pass through any fake blocks at will, so this method isn't fit for temporary mazes yet (yet). Perhaps it would work in the future, but there is much potential for stuff not working, if done strict.

**Comment by scorixear** [comment]
Oh, interesting, this way with lilypads.
it worked as I you said and I thought.
It is just a little bit to direct and instant, the smooth is missing. HAve you got any Idea, how to set the velocity to where they are also walking to (while gliding down). The getEyeLocation is a bad option for that (tested it and it did some weird stuff)

**Comment by asofold** [comment]
What values have you used for velocity ?

You could give the player an initial 0.42 same moment with sending the blocks changed to air. This would mimic jumping though. And then a little later you could send another 0.1 or so - can't really tell, without knowing what you've used.

**Comment by scorixear** [comment]
I do that:
`p.setVelocity(new Vector(0,-0.5,0));`
and I tried that:
` p.setVelocity(p.getEyeLocation().toVector().normalize().multiply(-0.5));`
But they can't really steer while gliding down

**Comment by asofold** [comment]
-0.5 might be faster than they are actually falling, perhaps try with something positive rather, or first something that resembles what they'll move like "soon".

I'd actually try a positive value for the first thing, or a small negative value like 0.15, not sure which effect you want to reach though.

MovingData.playerMoves contains information about how the last moves looked like, with quite some detail. This could be used to judge how they are moving (already falling or on ground or jumping). MovjngData.sfJumpPhase indicates how many moves they've been in-air. 

Unless you check during player move violation handling, the playerMoves will all be within past moves (index 0, 1, 2), and thisMove will not be set.
