### ISSUE TITLE
Elytra Bug Fix

### ISSUE THREAD

**Issue by ghost** [NoCheatPlus/Issues#433]
Basically i want the NCP to allow players to move in any way while they have elytra flying NOT just equipped, flying. You cant creative/survival fly while you are FLYING with elytra, even if u have hacks, so there is no need for flying to affect elytra. You cant vclip while FLYING with elytra either. This will stop the countless errors while using elytra like getting stuck head first in a block or using a rocket underwater.

#### Complete output of the _ncp version_ command (please prefer text here).

Part of the issue is using rockets underwater, sometimes you can fly into a block and get stuck, and sometimes you can jsut be using it normally and you freeze.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
I havent made any changes to the config.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

I dont use any other anticheats that affect movement. I use OrebFusicator though.

**Comment by asofold** [comment]
Flying with elytra allows some kinds of cheating as well, so we do need a check for it. Currently flying with elytra is handled by the creativefly check, but it should apply another model with other side conditions than with the ordinary flying (like creative mode).


The question is what kind of issues do you have?
* A known problem is with players who are already in creative mode, because the wrong model gets applied. EDIT: Might be fixed in build 1093 - refer to: https://github.com/NoCheatPlus/Issues/issues/266 or

**Comment by ghost** [comment]
I gave up on NCP and got AAC which fixes it completly. Sorry.
