### ISSUE TITLE
Add Staff Notify Command

### ISSUE THREAD

**Issue by CaptainObvious0** [NoCheatPlus/Issues#441]
This is a suggestion.

Be able to run a command like '/ncp notifystaff [player] failed [check]' that will act like a normal logging notify message but be able to run it as a command. It's very similar to the '/ncp notify' command but this will notify players with the notify permission. This would allow more opportunities with the command. 

Thanks

**Comment by MarkElf** [comment]
I suggested something very similar about a year ago on Spigot and got a slightly confused response. As I know where this is going, why not directly implement it into ncp. Have ncp's configuration offer a section where server owners can set a tps and ping value before sending a notification. I.e if player's ping is under 150 and tps is greater than 19.0, send the notify message to players with the permission node nocheatplus.notify.

**Comment by asofold** [comment]
@MarkElf What answer did you get?

At both:

Concerning tps and lag, i am not so convinced judging anything on based on the current state makes so much sense, because you would have to account for latency too, i.e. the client side latency or even detected lag (once implemented...) at a given time in the past. Similar could go for tps lag, because the relevant point of time to consider might lie in the past.

Practically tps lag (extreme) may lead to increased messages, and you could just randomly leave out some, same for high client side latency, which is not the same as lag, but which may correlate with lag often.

Concerning the issue text: Such a command could certainly be provided, supporting color codes with &, and also supporting (unless broken / until fixed) all the present tags during violation processing.

**Comment by CaptainObvious0** [comment]
@MarkElf Thats one of my uses for the command. I run any ban or kick commands through conditional commands which checks for tps, ping, and playtime. I also have a nocheatplus notify message when a player gets kicked or banned. No conditions are checked here. So if a player does not meet conditions with the ban/kick, then the notify message will be wrong. Using it to notify for a check will be useful for a few checks like MorePackets or Fly (Checking if they've been on the server for over x seconds).

@asofold Thank you :) This will be very helpful.

**Comment by asofold** [comment]
Things like "not been on server for more than X minutes/seconds (global/session)" could also  be part of ncp in future though. Not sure how to represent more complex conditions in the configuration.

**Comment by CaptainObvious0** [comment]
@asofold You could take a look at the plugin Conditional Commands. For example, if I wanted to execute /kick unless their ping was above x and they've been on the server for over x seconds, it would go along:
"cc [player] unless -ping->151|-time_online->30 do kick [player]"

That may be helpful.

**Comment by asofold** [comment]
Yes... the question is if to really do this kind of thing linearly or to flatten it out

Actions become very long this way - so one thing to consider is to allow defining arbitrary conditions/actions in a special section and reference them by some id, for one idea.

Another idea would be a different concept of 'default actions', possibly defined in a different file, or just implicitly. This could mean 'cancel' will always be included typically, and probably some generic log message (less specific than default), and to override (defualt) cancel, you would have to do so explicitly, e.g. via override:... - possibly all default actions would have some kind of an id.

**Comment by CaptainObvious0** [comment]
I think the arbitrary idea could be very useful along with the command. 

I'm not too sure about default actions since usually a lot of checks don't have the same commands, logs, or will even cancel. I'm a bigger fan of the other idea.

**Comment by asofold** [comment]
Yes, perhaps the main point with 'default actions' was intended to be 'have something default, in case none of the complicated conditional options apply' :). This should still be considered.

**Comment by MarkElf** [comment]
@CaptainObvious0 That's more or less what I meant. I didn't know that play time was a value that could be used, that may be quite entertaining to play around with despite the fact that vl can be built up within the first few minutes of playing with any hacked client. Play time may be best used with clearing high vls rather than checking for notifications/kicks/bans. 

@asofold I can't seem to find the thread after spending a bit of time looking for it; the thread may have been trashed for some reason. I want to say that we left off with you considering it but I don't honestly remember your response entirely. Since it wasn't made into an issue/ticket, it doesn't surprise me that it was forgotten about.

**Comment by asofold** [comment]
Especially with referencing conditions, things may become difficult to overview, so one could accidentally leave out cases - also what does apply if a conditions does not match - the latter is a question with conditions allowing to run multiple commands just like with VL>123.

So i'll have to extend the field slightly because some planned things are touched by this and i wouldn't want to reinvent wheels five times, having to revert 2-3 of the previously invented ones during progressing.

So i'll try to clarify where this may be going:
* Have generic VL classes.
* Support (arbitrarily complex) conditions, reference by an id. These allow combining conditions via boolean logic at first, accessing types of data - like typical data during violation processing, but also things like tps or violation level of a certain check.
* Conditions can be used to trigger sets of actions.
* (Sets of actions could again contain conditions?)
* (Later: have your own meta counters/vls only referenced via config, with conditions to trigger and actions to run.)

Considering this direction, there is no way to keep the on-liner actions definition, so i certainly want to think ahead a little bit here, even if we keep it a line + references.

Examples:
* Instead of _cmd:notify123_ something like **cond:oktps:true:**_cmd:notify123_ may be used. This would allow to group this under VL>456 alongside with other actions. At this stage this may be ok - there will be the question, how this turns out performance-wise (and how the configuration looks like), once you want to have the same condition for a range of actions. In theory this could be optimized within NCP, but this will be another level of complexity to implement and it needs to fit future changes/intentions very clearly, otherwise it'll mean a lot of boiler-plate-changes.
* Later we'll want to have sections of actions like with VL>... also for conditions, and you'd probably have nested sections (groups of actions).
* With a "pattern matching"-like situation, there certainly is the question for defaults, in case nothing matches. This could be a default section command default:..., which applies if nothing else applies.
* Another future change one might want to consider is judgements about severity, which certainly will use different methods to judge for different checks/environmental conditions :). This could be like vl>severe ...
* Yet another thing is to judge if a violation itself seems to be 'special' in terms of severity - to distinguish...
    * Just a little too fast/slow.
    * A follow-up violation.
    * Something like turning in-air. (Happens with lost-ground false positives often, though).
    * Something really crude, like a direct crash attempt or a very certain detection.
----
Of course the idea is not to design/foresee everything possible, but to keep these things in mind, to not have to redo everything thrice.

Concerning this ticket, perhaps the "single conditional action" with condition definitions referenced by ids will be ok to add.

The next thought might be, if we can really keep it one configuration file :) - i'd love to split off stuff (at least strings, definitions with ids to reference in general, a basic plugin config vs. check-related stuff, compatibility could be extra... also a complicated topic, thinking of multi world configs).

**Comment by asofold** [comment]
So with the direction "_single conditional action_ with condition definitions referenced by ids" we will have something like:
* Action syntax:
    * cond:cond_id:action
    * cond:cond_id:(true|false):action # Not sure here, could be useful.
* Condition definition:
    * conditions: ... cond_id: cond_def

----
A cond_def could look like _tps>12_  & ping<150, however the AND and OR (and NOT?) syntax will be another question - do we want to parse it like a programming language or will we simplify?
* A & (B | (C & D))
* Rather have flat definitions, where a definition can reference other definitions:
    * cond123: OR ? A, B, NOT C
    * cond456: AND ? D, X, cond:cond123, Z

(The former can/will also allow to reference cond:other_cond_id.)

----
The above question should be answered early on.

1. **For this very issue, simply adding the command doesn't really hurt (...).**
2. We'll want to add basic conditions to NCP.
    * player.time.session|played|... <> duration
    * tps <> number
    * ping <> number
3. Extend slightly to more interesting conditions for which NCP might have data.
    * ping/latency 'relevant to a violation' (actions only).
    * tps 'relevant to a violation' (actions only).
    * Time range for tps (average for the last 5 seconds or the 5 seconds before 'relevant to a violation')
    * Perhaps 'vl(check type) <> number' can be provided earlier on (even without transforming everything).
    * Might relate to server side lag spikes (probably increase resolution for past few seconds).
    * Should make possible to relate to tags somehow.

**Comment by asofold** [comment]
I'll split up the rest to another issue, like "INDEV conspetual: single conditional actions".

What i'll add will be a command to access logging features, restricted to console only use at first (note that _ncp log counters_ already exists):
* ncp log stream stream_id[@level] (...MSG...)
* example: ncp log stream NOTIFY_INGAME Hello &cstaff&f!
* MAYBE i'll add abbreviations like 'ncp log notify HEllo...' and 'ncp log debug XYZ'.

The command itself will not contain anything smarter than replacing color codes. If inserting the tags from violation handling poses problems, that would have to get fixed for command actions in general.

**Comment by asofold** [comment]
Build 1106 contains a new command, short version:
* ncp log stream notify ...

The command itself does not support color codes, so it is up to command actions in general to do replacing of color codes and other.

Also see here: https://github.com/NoCheatPlus/Docs/wiki/Commands#auxiliary-commands

**Comment by asofold** [comment]
Setting to fixed.

For single conditional actions see: https://github.com/NoCheatPlus/Issues/issues/444
For command actions this may be relevant: https://github.com/NoCheatPlus/Issues/issues/390

**Comment by CaptainObvious0** [comment]
Thanks for adding this in so quickly :)

The command is working great so far but I'm having a small issue. As you said the command itself does not support color codes. but when I use it as a command in the config, it will replace the  [player] [check] and [violations] variable but won't display any color codes. They will display as '&3' Am I doing something wrong or does this require a fix?

**Comment by asofold** [comment]
I need to look this up myself - are color codes supported with command actions at all?

If not... the question is if it's intended - if not i could let the log (notify) command replace colors OR i'll add another command action 'cmdc' which replaces colors ...

Perhaps there is some other oddity, with the other issue stating that [check]  not getting replaced.

After resolving the command/color issues, i'll probably just released, possibly tonight.

**Comment by asofold** [comment]
Build 1107 contains a 'cmdc' action, which is like cmd, just replaces color codes.

**Comment by CaptainObvious0** [comment]
That seemed to fix it. Thanks :)

**Comment by CaptainObvious0** [comment]
After working with the command a little more, is it possible to do two streams at once? Such as in game and console.

**Comment by asofold** [comment]
With a command currently not. Could add comma-separation for the stream(s), so the command could do it. Or would '+' be better ?

An issue with this is, that the behavior will be different to log actions, because log actions would strip color for the console or file, so logging the same message with colors in would be different.

Perhaps some solution could be there, not sure.

**Comment by asofold** [comment]
Build 1109 contains a change to allow both logging to multiple streams and to force replacing or removing color. Description updated: https://github.com/NoCheatPlus/Docs/wiki/Commands#auxiliary-commands
