### ISSUE TITLE
Minecraft 1.12-pre2

### ISSUE THREAD

**Issue by ghost** [NoCheatPlus/Issues#445]
Hey

On latest version (Pre version released from Spigot) I'm getting http://paste.yu8.me/?c0315f5d51b343d2#/f914hvcklKC3OILj34WLbCFTQFhqlAF14SJzPOX3PY=

Just giving you a heads up before 1.12 is released

**Comment by asofold** [comment]
Build 1108 contains the (supposedly) minimally required changes to run with 1.12.
* Detect MC 1.12-pre as 1.12.
* Blocks added (not tested much).
* (ProtocolLib 4.2.2 allowed. For me build 357 crashes the client on localhost, even before connecting, using 127.0.0.1 doesn't crash the client anymore, but the client can't connect due to an exception. I assume this will be fixed by the maintainer soon.)

Edit: With build 1110 i've removed ProtocolLib hook activation, due to issues. Haven't tested if it helps at all... give me a minute.

**Comment by asofold** [comment]
Build 1111 will re-enable ProtocolLib - appears to work from ProtocolLib 359 on, however there still is an exception thrown from ProtocolLib, likely to get fixed soon-ish too.
