### ISSUE TITLE
Nocheatplus update

### ISSUE THREAD

**Issue by MrFadeFancy** [NoCheatPlus/Issues#447]
#### Short description of the issue.

- Hey, I have downloaded the plugin but it is blocking small hacks but its not blocking big hacks like Killaura, Speed, Reach(up to 5 blocks cant be detected like wtf?)

#### How to reproduce the issue (is it random / always happens / side conditions)?

- Some hacked clients bypass it with YesCheat++ then they can bypass it like wtf?

#### Have you made any (noteworthy) changes to the default configuration of NCP?

- yes, I got a custom config.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?

- No

**Comment by MarkElf** [comment]
The output of /ncp version would be nice to identify server version, ncp build, and additional details. 

A debug log would be ideal here with the default configuration. Information on debugging is linked just above. 

Ncp takes steps to limit kill aura and create an even pvp environment between a hacker and an average pvp'er. There are no messages that directly state 'this player is using kill aura' but it's suggested by the existing notifications, most checks in the combat section server this purpose. I haven't run into a client that bypasses the existing speed check or reach limit; debug logs would be great here.

**Comment by asofold** [comment]
Small / big is subject to interpretation and server style :). 

For judging cheats we rely on the facts around what they can do more than a legitimate vanilla client (not necessarily with a professional playing it). So it's not enough to scare me telling me some cheat client can activate cheats - i'll want to know what they can actually do on what field.

* YesCheat1q23 is just an optimized switch for adapting checks to NoCheatPlus on the server. All plugins are different and may allow different 'optimizations' on client side. This says nothing, except that NoCheatPlus is used by a considerable lot of people, so some clients have a special switch.
* Killaura - see what @MarkElf wrote. NCP limits it - typically the default settings are too strict for real pvp servers so they get alterered, also resulting in less protection. In general the fighting checks are still subject to overhaul though, there is a few changes queued.
* Speed - 'ncp stopwatch distance 100' on flat ground <- that's our reference. Currently we limit around 15% speed up max for horizontal speeding. This is subject to overhaul too, including how people can strafe and change direction.
* Reach (fight?) - Doesn't in general allow 5 blocks - HOWEVER, since fight checks overhaul got delayed, there is more defacto leniency built in, because we allow hitting past positions, _in order to account for latency_. Per position it's quite precise by now (not the latest technology built in though), currently NCP allows 15 ticks difference (650 millisconds!) - two points to consider:
    * The checks for past-position hitting are unfinished, because maintaining a latency window+best-guess has not yet been implemented - this will confine the player to not being able to shift by too much time with their actions, including cross-checking with other things like packet response times. Future update.
    * The fight-check related settings are not yet configurabel (due to not being implemented). It's possible to reduce the maximum age of past locations with setting _checks.moving.trace.maxage_ to something lower (in ticks a 50 ms).

Roadmap:
* Next: i'll just release the current state with preliminary 1.12-pre support
* I'll make roughly one attempt per false positive listed in the roadmap document: https://github.com/NoCheatPlus/Docs/wiki/Roadmap#current-focus
* On the fly i'll adapt to 1.12 (-pre) based on reported issues.
* As you can see further down on the roadmap page, a range of changes (partly experimental) are queued, including fight checks and the past-location stuff (somehwhat randomly ordered!): https://github.com/NoCheatPlus/Docs/wiki/Roadmap#scheduled

(Setting to duplicate, since most/all touches existing issues - not always in a direct way, but on schedule anyway.)
