### ISSUE TITLE
Error on player join

### ISSUE THREAD

**Issue by MarkElf** [NoCheatPlus/Issues#506]
#### Short description of the issue.
Console displays an error each time a player joins. 
#### Complete output of the _ncp version_ command (please prefer text here).
https://i.imgur.com/JOmsUg1.png
#### How to reproduce the issue (is it random / always happens / side conditions)?
As said above, each time a player joins. 
#### Have you made any (noteworthy) changes to the default configuration of NCP?
None.
#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
None. 
#### Provide additional information, such as error/debug/violation logs. (For reproducible issues with moving consider: https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players) Use GitHub gists or http://pastebin.com/ or similar for huge logs, or attach a (zip-) file here. For image uploads, please prefer a site that allows viewing without JavaScript, you can upload file attachments for issues right here.
-

**Comment by asofold** [comment]
What error is showing? I can't reproduce...

**Comment by Janmm14** [comment]
@MarkElf You rpobably forgot to add the error

**Comment by MarkElf** [comment]
My bad. The error can be found here: https://i.imgur.com/jqtBXHv.png 

I've also gotten this message which I am curious about. https://i.imgur.com/47mBZzJ.png

I'll try the least development build to see if it sorts out the issue soon.

**Comment by asofold** [comment]
This error message indicates that another plugin causes a standard event to fire asynchronously, i.e. off the primary server thread, for the case of events that don't ever fire asynchronously for a standard Spigot server.

For all cases i have observed so far, it's not something you want to keep (vehicle enter/exit, teleportation, inventory action), because related event handling by other plugins can't be expected to be thread-safe, besides the Minecraft server and Spigot are not explicitly stating to be thread-safe for those actions either - in fact the Bukkit-API states that everything that isn't explicitly stated to be thread-safe, is not thread-safe. An exception could be to ignore such events (risky, because we can't know if a plugin prematurely "optimizes" things, leading to safety issues, because our checks don't run and can't check the map state at the destination) or we just prevent those events by cancelling (the other plugin can't work either, and probably the server is broken, e.g. if the teleport is necessary for game play).

A workaround is not really feasible for the general case, risks of asynchronous actions like that are data corruption and server hangs.

The other plugin (a.b.c...) looks heavily obfuscated, no idea what it is. Note that sometimes events are caused by other event, e.g. vehicle exit is caused by a teleportation and vehicle exit is followed by a server-side teleport.

**Comment by MarkElf** [comment]
I appreciate the explanation and take taken to respond.
