### ISSUE TITLE
Unexempt BUG

### ISSUE THREAD

**Issue by alvarocduquia** [NoCheatPlus/Issues#512]
Hello, I'm having a problem with NoCheatPlus. To fix a bug in my Sky Wars plugin, I need to exempt a player from NO_FALL, this is working. The problem is that when I go back to unexempt, the player receives the cumulative damage from NO_FALL. Is there any way I can remove this damage by the API?

Version:
![image](https://user-images.githubusercontent.com/8584714/35713175-076e7986-07ad-11e8-8802-e6464099ccf8.png)

**Comment by alvarocduquia** [comment]
Solved.

![image](https://user-images.githubusercontent.com/8584714/35723958-42b3982e-07e3-11e8-9b0d-d2703e5a4705.png)

**Comment by asofold** [comment]
This kind of issue hasn't been brought up yet, but it's good to have it. Currently exemption does only prevent code from running, but does not reset the data. In case of NoFall it's a problem.

MovingData does have a clearNoFallData method though - it might be better than just resetting the fall distance, because the maximum y-coordinate reached is stored there too.

I'll soon reimplement exemption, and it may be worth a shot to consider extra handlers for exemption/unexemption.

**Comment by alvarocduquia** [comment]
Good, thx!
