### ISSUE TITLE
High TPS usage

### ISSUE THREAD

**Issue by BBoyJD10** [NoCheatPlus/Issues#513]
High TPS issue

https://gyazo.com/915c578a4973250edb823e90512eb988

**Comment by MarkElf** [comment]
Provide the full output of /ncp version.

**Comment by BBoyJD10** [comment]
https://gyazo.com/fc8e362ae98adc083fdd97e2ca6af186

**Comment by MarkElf** [comment]
Try using the latest public release as the recent development builds haven't been stable or build 1136. There isn't going to be a large difference since it's 2 builds apart.

**Comment by asofold** [comment]
The latest builds contain some internal changes which might be problematic on a production server - that's why they're marked as [BREAKING][BLEEDING][INSTABLE] :).

I've been testing around for a while and it "looks good", though.

Concerning this very issue, i strongly suggest to have a look at the data, before taking any further decisions.

Concerning these timings, the following can be said:
* The post enable task runs once, directly after server startup.
* The sample size is way too small to say anything. Any time the server or java can interrupt your thread for 300 milliseconds easily, especially after starting up. Until the JIT is warmed up, some time will have to pass with server load on. For a small server you'd want 200000 PlayerMoveEvent-s, for a bigger one you'd probably prefer 1000000 and many more.
* Currently NCP might take somewhere between 0.5 to 5 % of a tick with full checks enabled, depending on further hooks (count to performance of NCP...) and on the type of server (a percentage of players is moving, all are moving and fighting, ...).

In this case with a maximum event count of 82, the data says nothing, except that the PostEnableTask is running once and taking up a long time - this task runs once per runtime only and should be ignored :).

**Comment by mibby** [comment]
@asofold I was also just about to create a ticket for high TPS usage, but for the post-enable task. :P Using NoCheatPlus dev 1141.

```NoCheatPlus::Task: fr.neatmonster.nocheatplus.NoCheatPlus.PostEnableTask (Single)```

![link](https://i.imgur.com/Mb9TNTs.png)

Is there nothing that can be done to optimize the initial loading of NoCheatPlus? While it may only happen once, I have users automatically reconnect to the server when it goes through an automated restart by keeping the connection alive on the proxy (BungeeCord). However because of the initial lag, it takes a couple seconds to stabilize before players can load in, get their profile / groups loaded, and walk around fine again.

**Comment by MarkElf** [comment]
@mibby There is an option to increase the delay before players join in the configuration.

    logins:
      active: true
      startupdelay: 300 #increase this value.
      perworldcount: false

**Comment by mibby** [comment]
@MarkElf I don't want to force clients to wait longer to connect though. I want people in as soon as it is safely possible, since I hold it pending on the proxy with a keepalive timeout, then reconnect when the server is back up. The lag is only really an issue on initial start-up when everyone is forced back on the server all at once automatically.

I do use ```  late-bind: true``` in Spigot settings so players can only connect after all plugins have loaded.

**Comment by asofold** [comment]
@mibby I don't fully understand the display of timings there - one event takes more than six seconds ?

That would really be a lot. Past reports indicate that usually such is due to permission recalculation - NCP will set some generic child permissions for all checks for instance, but the "command protection" feature might also add new permissions. Problems used to happen with command blocks, though i thought that had been fixed.

Even debug logging shouldn't affect things like this.

(Edited something away.)

**Comment by asofold** [comment]
(...)
Is there a log message after restart with stating "Updated data for ... players (post-enable)"?

So what will happen ...
(...)

Next build, all default child permissions (check .silent and command filter) will be defined in the plugin.yml. For notifications only permission subscriptions will be in use (if some important server version needs something else, might add a fall-back thing.)

**Comment by mibby** [comment]
@asofold Performance seems to be a bit better as of commit https://github.com/NoCheatPlus/NoCheatPlus/commit/cec4a4d129ad04df40c8d78cc7d5661049332567

![link2](https://i.imgur.com/3EaV7rM.png)

This was only tested with 6 people online at the time of restart and forcing them to reconnect. More people may have a bigger impact -- I'll give it another test later in the day.

**Comment by asofold** [comment]
Assume resolved for most :) - feel free to note if not/something.
