### ISSUE TITLE
Dirt block pullback

### ISSUE THREAD

**Issue by LoXR** [NoCheatPlus/Issues#532]
#### Short description of the issue.
On plowed Dirt, if you run and jumped it will pull you back.

#### Complete output of the _ncp version_ command (please prefer text here).
NoCheatPlus Version 3.16.1-SNAPSHOT-sMD5NET-b1143

#### How to reproduce the issue (is it random / always happens / side conditions)?
Use a hoe on multiple dirts (or make a farm) run and jump and you'll see what happens.

#### Have you made any (noteworthy) changes to the default configuration of NCP?
No.

#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?
Only use Spartan anticheat for combat, nothing to affect Movement checks as all of them are disabled. No logs were made if it was Spartan causing this.

**Comment by asofold** [comment]
Can't reproduce at first.

Could you edit to the _full output_ of the _ncp version_ command? Most of the contained information is crucial to judging, specificlally:
* Server version.
* Detected Minecraft version.
* Extra plugins like multi protocol support plugins.

Does it happen for all clients or only with multi protocol support for certain client versions (other than server version)?

**Comment by LoXR** [comment]
NCP Version: NoCheatPlus version 3.16.1-SNAPSHOT-sMD5NET-b1143
Server Version: git-Paper-1389 (MC: 1.12.2)
Detected Version: 1.12.2
Protocols: ProtocolLib, ProtocolSupport, ProtocolSupportStuff

**Comment by asofold** [comment]
I'm very sure this is due to protocol support plugins. With minecraft raising or lowering a block height, protocol support plugins probably force use the lowest one server side, in order to prevent the vanilla server freezing players. There is a patch inside NCP which is supposed to catch this, though - so:

(1) Does the server log or nocheatplus.log file show a line starting with this: "Applied block patches for multi client protocol support:" ?
* If yes, please post that line, inlcuding the block types it states.

(2) Does it happen immediately/always or just after a (short) while of sprint-jumping?

**Comment by LoXR** [comment]
1. Couldnt find anything apart from this being spammed: 18-04-02 22:06:44 [SEVERE] Off primary thread call to hasByPass for INVENTORY_OPEN See earlier in this log, search for -> log once id=1365228838

2. And its has a delay after sprint-jumping.

**Comment by asofold** [comment]
I'll test with a larger blotch/lane of those blocks. 

Likely this is due to protocol support altering block shapes, which 'confuse' some of the jump-tracking within NCP. If i can't reproduce it, i'll need someone to produce a debug log (https://github.com/NoCheatPlus/Docs/wiki/Debugging#on-the-fly-debug-output-for-individual-players).

**Comment by asofold** [comment]
If a soil block transdorms to dirt, false positives will happen also without any multi protocol support - not sure i understood the initial issue description "dirt block pull back".

**Comment by LoXR** [comment]
Basically plowed dirt, used in farms. If you trample on them and jump, it will cause the pull back.

**Comment by asofold** [comment]
So the issue only is with the block changing back to dirt?

I'll fix that in any case (reproduced without multi protocol support).

**Comment by asofold** [comment]
Build 1147 contains a fix attempt. Needs the block change tracking to be enabled (default).

**Comment by asofold** [comment]
(Assume fixed.)
