### ISSUE TITLE
Non-vanilla behavior when running ncp (several minor movement issues bunched together)

### ISSUE THREAD

**Issue by MarkElf** [NoCheatPlus/Issues#538]
Post on behalf of @Joe7670 .
The following has shown to be inconsistent between vanilla and when ncp is ran. 

/ncp version output:
#### Server ####
git-Paper-1384 ~MC: 1.12.2~
  detected: 1.12.2
#### NoCheatPlus ####
Plugin: 3.16.1-SNAPSHOT-sMD5NET-b1144
MCAccess: 1.12-1.12.2 / Spigot-CB-1.12_R1
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
  checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
Hooks: AllViolations~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.3.0

1. Flying straight into the ground with an elytra (literally straight down) causes no (fall) damage to be taken when it does in vanilla. I'm not aware of how this can be exploited entirely, but just throwing that out there.
See video: https://youtu.be/k7x0CnUdxko

2. Players are unable to trample farmland blocks by jumping on it due to the survivalfly check

3. Falling 3.5 blocks deals no damage to the player while it does in vanilla.

**Comment by asofold** [comment]
1. I assume this isn't strictly fall damage but the kind of damage they receive for bumping into walls sameway - not sure it's actually modeled as fall damage, though. 

2. Due to survivalfly !? How does it interfere?

3. NCP should deal damage from above three blocks fall height by design - maybe a bug.

Edit: IT changes the numbers in a SMART way.

**Comment by MarkElf** [comment]
Regarding trampling crops, it does seem to be related to survivalfly. After adding "nocheatplus.checks.moving.survivalfly" via console, I was able to trample crops again. It also seems to be survivalfly that is responsible for 3.5 blocks not dealing damage.
Video showing both: https://youtu.be/N8iOx2A176w

**Comment by asofold** [comment]
(3.) Concerning fall height, it's been a minimum damage amount set to 1.0. Altering that to 0.5 allows dealing damage for 3.5 height now. Build 1146 will contain that change.

(2.) I've been wondering about crop trampling on my local test server, because it never seems to happen - the question is why / how. Perhaps fetching the shape is done wrongly and it's a method that prevents changing the block in that tick via trampling, but still returns the shape ... depends. Can it be nailed down to MC 1.12.2 ? I think it's been this before.

(1.) Does NCP prevent the damage to happen, or is it about cheats?

**Comment by MarkElf** [comment]
1 - As I mentioned, I'm not sure if or how it could be exploited. NCP just prevents damage from being taken which is something to note. It's up to you if it's worth patching or not. I personally don't mind it. It's not currently related to any cheats as far as I am aware.

2 - I just tried paperspigot 1.8.8 and it seems to happen with that version as well.

**Comment by asofold** [comment]
Looks like my message did not get posted here.

(1.) Ok... i bet there are exploits possible to not take damage, but other cheats could also prevent the damage in slightly more smart ways, because monitoring the exact way of gliding isn't too far developed, besides punishment currently is to teleport a couple of blocks back... so they could simply cause a violation and continue slow gliding from a couple of blocks away.

(1.) Crop trampling confirmed - as OP i can trample, with survivalfly nothing happens. Perhaps the method of shape fetching actually _updates_ the block somehow, so destruction via physical pressure or whichever way it's modeled isn't possible (speculation ...).

**Comment by Joe7670** [comment]
Asofold, Are you sure you understand the first issue?  The issue is that players can use NCP as a means to avoid fall damage because it prevents it from happening when flying straight down. It doesn't have anything to do with cheats. Are you saying this happens because the player triggers a false positive when hitting the ground thus interfering with the fall damage?

**Comment by asofold** [comment]
Avoiding fall damage with a vanilla client may be an interesting point.
* The "typical" situation for elytra means having a lot of space, so even a vanilla player could steer such that they don't have to take any fall damage.
* The above simplifiction doesn't go for special situations.
    * Hitting a very small platform without taking fall damage, where you otherwise could rather not land on.
    * Avoiding fall damage within a chimney like setup.
* Connection with cheats always is: Can cheats do the same in a simple way. So it's not so far fetched to compare to likely to be implemented cheats. In this case a cheat could provoke a violation just before hitting the ground and thus reduce damage by near 100%, because they'll start over from 0 speed after having been set back by a few blocks. Working around that would need pulling players to ground below and dealing damage somehow, however that's problematic with false positives concerning elytra in general.

The damage being dealt there technically is from the flying speed, am i mistaken?

**Comment by asofold** [comment]
Closign as superseded - split to multiple issues.

Fall damage: fixed in build 1146 from 3.5 fall height on. (Build status is still 'bleeding'.)
Elytra: https://github.com/NoCheatPlus/Issues/issues/540
Farmland: https://github.com/NoCheatPlus/Issues/issues/541
