### ISSUE TITLE
Having some issues from fr.neatmonster.nocheatplus.utilities.TickTask 

### ISSUE THREAD

**Issue by hurrgurl** [NoCheatPlus/Issues#542]
**#### Short description of the issue.**
https://i.imgur.com/jzRN16T.png

What is it? Please point me in the right direction.

**#### Complete output of the _ncp version_ command (please prefer text here).**

[01:25:35 INFO]: ---- Version information ----
[01:25:35 INFO]: #### Server ####
[01:25:35 INFO]: git-Paper-1399 ~MC: 1.12.2~
[01:25:35 INFO]:   detected: 1.12.2
[01:25:35 INFO]: #### NoCheatPlus ####
[01:25:35 INFO]: Plugin: 3.16.1-SNAPSHOT-sMD5NET-b1143
[01:25:35 INFO]: MCAccess: 1.12-1.12.2 / Spigot-CB-1.12_R1
[01:25:35 INFO]: Features:
[01:25:35 INFO]:   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10
 BlocksMC1_11 | BlocksMC1_12
[01:25:35 INFO]:   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter | AttackFrequency | FlyingFrequency | KeepAli
eFrequency
[01:25:35 INFO]:   defaults: pvpKnockBackVelocity
[01:25:35 INFO]:   packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
[01:25:35 INFO]: Hooks: AllViolations~NCP~ 1.0
[01:25:35 INFO]: #### Related Plugins ####
[01:25:35 INFO]: ProtocolLib v4.3.0

**#### How to reproduce the issue (is it random / always happens / side conditions)?**
Never had any issues with NCP before, the server was online for a week before this issue showed up in timings.

**#### Have you made any (noteworthy) changes to the default configuration of NCP?**
None

**#### Do you run any other special plugins that affect game mechanics next to NC+ (adding skills, machines, adding/changing blocks, other anti cheating)?**
No

**Comment by asofold** [comment]
First off, i don't fully understand the timings display (count , ...) - if i understand right, the tick task consumes a millisecond per tick in average, which is a lot in general, and which would be an even greater lot, if the high values originate from the last hours/day of a week uptime. 

If you look at the side bar of the changes list on the Jenkins location, build 1143 is marked as _deficient_: https://ci.md-5.net/job/NoCheatPlus/changes

The issue would certainly impact the TickTask processing, potentially amassing with the amount of players that have gone through your server, thus typically increasing over time.

You should update to build 1146 or later rather (or downgrade to an earlier non-_deficient_ build). In any case, with running the latest of development builds, please check the change list now and then, at least for if the build you're running has been marked as _deficient_.

Perhaps i should add an auto check thing, that notifies in such a case.

**Comment by Janmm14** [comment]
The timings v3 by aikar do just show ticks needing >50ms (laggy ticks) by default.
It reads as 126.74ms average per execution on a laggy tick and it is executed 1.01 | 0.99 times per laggy tick tick.

**Comment by asofold** [comment]
@Janmm14 Thank you.

In that case the figure shows something like 'there has been ~ 180 times with the tick task taking way too high amounts of time'.

For an uptime of a week, that would be slightly more than once per hour, provided it's distributed equally.

It could still be the issue, as that build can produce a NullPointerException, and from then on will always produce that exception, whenever the sub-task is run.

Remains to be seen, if it's due to the NPE:
* The run 'the sub task for this UUID' collection is getting larger and larger.
* Certain permissions are not updated, thus update requests are made each and every time such a permission is tested (rather net checks / chat).
* (On the other hand, the loop is aborting at that UUID, where the PlayerData had been removed, thus the iteration remains somewhat limited.)

Possibly the permission updates for the net checks could get nasty, because scheduling those means some synchronization. It does depend on the permission caching configuration, but assume all players who have changed the world once, have their permissions for the net checks outdated, and the update is scheduled to be executed within the primary server thread. Therefore the TickTask (primary server thread) will at least have to merge in the update requests with one time lock access, which can get preempted easier, if permission updates are requested for many players from within the networking threads (...) all the time.

So after writing down random thoughts for so and so time, i'm somewhat optimistic that it'll be better after updating to the latest build.

The entire impact of permission caching remains to be seen, some measures have actually been built in, in order to cut down the maximum impact on the primary server thread, but still.

**Comment by asofold** [comment]
Assume fixed by the latest builds.
