### ISSUE TITLE
Passable check failing to detect a lot of exploits

### ISSUE THREAD

**Issue by bob7l** [NoCheatPlus/Issues#59]
Version: Build #9​04
Minecraft Version: Spigot - 1.7.10 [Last build]
Server status: 20/20 TPS
Latency: Within 100ms

Config:
    passable:
      active: true
      raytracing:
        active: true
        blockchangeonly: false
      actions: cancel log:passable:0:0:cif vl>4 cmd:kickandteleport cancel
      untracked:
        teleport:
          active: true
        command:
          active: true
          tryteleport: true
          prefixes:
          - sethome
          - home set
          - setwarp
          - warp set
          - setback
          - set back
          - back set

This is a current issue with the latest NoCheatPlus builds. Players are able to exploit a bug and phaze into houses built out of stairs without a single passable detection from NoCheatPlus. The first Video requires no external hacks, or 3rd party mods. 

Video #1 (NO hacks)
https://www.youtube.com/watch?v=T2jz0vnmCO0

Video #2 (1.7.10 client) (Resilence hack client, Fly + Freecam)
https://www.youtube.com/watch?v=n3YmPm_o-Nk

**Comment by bob7l** [comment]
I made it so if the violation level is above 4 it kicks just so you can see that the passable check appears to be completely ignoring my attempts shown.

**Comment by asofold** [comment]
What does the cmd:kickandteleport do? Level 4 is _very_ low and can easily be reached after join or fart teleport... unless we can reliably distinguish the 'slow falling' after join/teleport, one shouldn't do anything severe on such low violation levels. Question remains: where does it teleport to?

With the second video i am not entirely sure: they are using a block placed at the foot position of the player, is the 1x1 channel completele free at that point, so the player is just moving out of that block with their feet?

Are there other plugins involved that might 'optimize' or 'correct' locations or such, e.g. on teleporting?

**Comment by bob7l** [comment]
It'll teleport the user to the spawn and kick them at level 4. I added this simply to show that passable is not throwing any violations while the user is going into blocks. 

The second video i'm still not EXAcTLY sure how he did it (He speaks spanish, hard to talk to hm). I believe he just used Freecam to remove the blocks along the block mass he made to make a proper walk way. He then placed a block inside his current location and somehow moved from there. 

The server uses one plugin developed by me. Neither the onmove event, or the playerteleport event are touched. 


Also, i haven't checked the code of NoCheatPlus yet but do you by chance us NMS and bounding boxes for a lot of these passable checks? It has many features to allow for ray tracing which doesn't ignore things like stairs. You could easily throw it on the PlayerMoveEvent using from and to (If you don't already do that).

**Comment by asofold** [comment]
The question with the second video would be, if they moved just out of one block, or through another block with the foot position. Blocks placed at head height are not considered anyway, except for if moving upwards. (Subject to future changes, but now we only consider the foot position).

We don't use too many nms methods, mostly for block shapes. We do some kind of ray-tracing, but we only use the foot position (for performance reasons, think of 500 players and 20 moves per second... thus we use a cache-like thing, which doesn't fetch stuff twice). For the moving of players you actually go y first then x/z then  z/x, so for most it might be pretty simple to change to full bounding box checks.

For the first video i can't tell why they can get through there, need someone to reproduce that at will and produce a debug log of it.

Do you have ProtocolLib (if so, which version) ?

**Comment by bob7l** [comment]
I'll see if i can contact him to see exactly how he did it. He might even make a video of it. 

The player instance (Like all entity instances) contains a dynamic bounding box that is used for collision detection in vanilla. This bounding box moves with the player, and checks for collision every time the entity moves. They use it for collision checking every tick for just about every entity so it can't be that big of a performance impact. 

You could easily do the following to check for collision:

List<AxisAlignedBB> list = this.world.getCubes(this, this.getBoundingBox().c(d0, d1, d2));
for (AxisAlignedBB axisalignedbb6 : list) {
	if ( axisalignedbb6.b(player.getBoundingBox().c(moveX, moveY, moveZ))) {
        //Collision with blocks!
    }
}

It's efficient, and instead of using a location, it accounts for the actual player. And once again, i haven't personally looked over the NoCheatPlus code so i may be suggesting something that you've already tried. 

I use ProtocolLib 3.6.0-SNAPSHOT for 1.7.10.

**Comment by asofold** [comment]
Please consider updating to ProtocolLib 3.6.4! It supports most versions of Minecraft and NCP is built against that. This shouldn't affect passable directly, but there might be other issues in theory (though NCP doesn't activate ProtocolLib hooks with 3.6.0).

There are various reasons why we won't use all 'available' nms methods:
* Entites do eat up a lot of performance, though mostly for ai. We have to keep the plugin below 1-5% of a server tick, so we can't just 'do what the client does' or similar.
* The client doesn't send the full truth, we might have to re-check a couple of times.
* Not even the server will always tell the full truth, e.g. on block shapes. We override a lot of shapes. There may be lots of special cases for players on client side, which the server won't account for with ordinary entities.
* We have to re-check multiple properties of the involved blocks (or of other nearby blocks), speaking of water, lava,  slime blocks, fences, ray-tracing, head blocked, sides blocked. Performance-wise you'll get to a point when using getCubes, including object creation will not be that nice to have overall.
* We will have to account for past-changes on blocks, in order to make doors both safe and playable, same with pistons (future, but queued). There we do need an optimized structure.
* On Minecraft updates people run the old plugins, we prefer to go towards _mod-independence_ rather (very long run), so basic features of NCP stay available after a server update. (We do have a reflection based module for nms, which might by now cover minor updates for most.)
* (More) Mod-independence is also a topic for the (future~) check design.
* Possibly forgot half of the reasons, but it's not just one time scanning a couple of blocks. So our way will rather be making block shapes fully available by configuration and being able to run without any nms, in theory.

The point for these issues (except for a 1x1 air gap on foot level) would not be the bounding box, but the code of the check rather (provided there's not another plugin optimizing positions on teleport somehow).

Another thing: If the players don't trigger passable at all, something fundamental must be wrong. To really find out we'd need someone to reproduce the issue with a debug log taken (https://github.com/NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players).

**Comment by bob7l** [comment]
Oh wow i wasn't even aware Protocollib 3.6.4 existed lol. Thanks for that, i'll defiantly be updating. 

Yeah i figured NoCheatPlus has already messed around with just about everything. Thanks for explaining. 

And i'll trying to get a debug log for you as soon as possible.

**Comment by asofold** [comment]
Has this been observed anywhere (+else) since build 914/920?

**Comment by asofold** [comment]
Could any of these be reproduced/clarified/debugged by anyone yet?

**Comment by asofold** [comment]
How about this one? Could anyone reproduce any of this with recent development builds?

**Comment by asofold** [comment]
Build 1005 introduces a new method, thus closing as 'fixed' in terms of 'outdated'.
