### ISSUE TITLE
Uncompatibility with WGFlyFlag

### ISSUE THREAD

**Issue by Kixot14** [NoCheatPlus/Issues#63]
When players with activated Fly Flag go out of their region, he tooks damage and sometimes even die. It's cause NCP kills her. CAn u do something with that ??

My server version: CraftBukkit version git-Spigot-2f787bd-ea28011 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT

WG flyFlag link http://www.curse.com/bukkit-plugins/minecraft/worldguard-fly-flag#t1:description

**Comment by asofold** [comment]
Is there a reason to stay on 1.8.3 instead of (latest) 1.8.8 for the server version?

What is your version of NCP? You could just paste the full output of the '/ncp version' command, so we can quickly judge.

People take damage, moving out of the region - damage after falling or just walking on ground?

**Comment by Kixot14** [comment]
Don't use latest spigot version, cause some my plugins is not up to date yet and works not correctly.
Today i updated NCP to latest version. but problem still actual!

It's not happen always (only in 30-40%)
Most often it happens when people(without op, of course) just flight(with FlyFlag) / walking on the ground and go out of their region on the bottom or on the top line, with jumping.

When it's happen, NCP sent request about 'failed SurvivalFly: tried to move unexpectedly. VL 100-200.'

**Comment by asofold** [comment]
1. Might try build 907, though it might contain other issues (rather larger changes). 
2. The fastest thing might be to set checks.moving.survivalfly.setbackpolicy.falldamage to false, in the hope that it resolves the issue (prevent dealing fall damage on survivalfly violations).

**Comment by asofold** [comment]
For the case they just accumulate fall distance server-side, we might be able to do something.

If it's about falling and latency, having the client receive the fly-off notice after having sent more moves, it could be near impossible to mend, because the players will always move on before receiving the fly-off notice. A flying plugin could ensure fall damage is undone for the transition, but i don't think that NCP can do that.

I need someone to reproduce the issue and create a debug log, if possible for both cases (falling/walking).  Current reference is build 813 (latest).

**Comment by Kixot14** [comment]
FlyFlag prevent fall damage, but only inside WG region with this flag ;[
So only one way to fix that - is do disabling fall damage in place, when players go out of their regions ? (Orr if author of FlyFlag add a something like buff, which prevent player for falling damage at 3-5 sec after Fly-mod disabled?)
P.S. not really understand what u mean under "create a debug log"? Wheare this is enable ?

**Comment by Kixot14** [comment]
" i used to use a flying plugin + RSP (region specific permissions), where the flying plugin would prevent fall damage after switching."
So this RSP just removed and add some perms for specific groups, when you cross the region??
But for that need a fly plugin, which have permission with which fly for players always active. What exactly flight-plugin you use ??

And maybe you know way, how possible to disable fall damage for some groups for a few seconds, when player cross the region ??

**Comment by Kixot14** [comment]
In build 914 issue still actual :[

**Comment by asofold** [comment]
We need to find out, if there is any out of the ordinary damaging there. Concerning walking and death by fall damage, i'd like to know, if that's a 'real thing', or if that's just the impression the player had due to latency. E.g. the player flies down and walks, then dies of fall damage - impression is death by walking, but the player may have been outside of the fly region before touching the ground.

I'll push a build with resetting the fall distance on that fly-nofly transition,  which might solve some cases.

**Comment by asofold** [comment]
Do latest builds change anything here? Can anybody else reproduce this with a minimal test setup (possibly a remote server with some latency needed)?

**Comment by asofold** [comment]
Does this improve with build 920?

**Comment by Kixot14** [comment]
Sorry for no answer. I was very busy at last days. I try iy over today-tomorrow!

**Comment by Kixot14** [comment]
Looks like all is fine with build 920. Thank you for fix!
P.S. All in my NCP config is set to default. Do i need to change anything? Or it's not necessarily ??

**Comment by asofold** [comment]
No need to change much - unless some of your concepts is too much affected by false positives. Fight checks will be much changed, currently some people prefer to turn off penalty time in some checks.
