### ISSUE TITLE
NCP kicks for flying when on barrier block

### ISSUE THREAD

**Issue by adamwbb** [NoCheatPlus/Issues#65]
there are barrier blocks on the sevrer and we noticed that NCP will kick players if they are on a barrier block.
28.12 23:56:11 [Server] INFO MCAccess: 1.4.6|1.4.7|1.5.x|1.6.x|1.7.x / Bukkit-API
28.12 23:56:11 [Server] INFO Plugin: 3.11.1-RC-sMD5NET-b743
28.12 23:56:11 [Server] INFO #### NoCheatPlus ####
28.12 23:56:11 [Server] INFO git-Spigot-44c59bf-8f0f4ed (MC: 1.8.7)
28.12 23:56:11 [Server] INFO #### Server ####
28.12 23:56:11 [Server] INFO ---- Version information ----

**Comment by asofold** [comment]
For 1.8.x you need to update NoCheatPlus to the latest Beta (BukkitDev or marked as recommended on Jenkins). If one of the latest changes might be useful (e.g. 2-high ceilings, slowness), you could consider switching to a development build around 906 or 907.

If you are using CompatNoCheatPlus, you will have to update to build 83 as well.

If you are using ProtocolLib, we recommend to use ProtocolLib 3.6.4 or later with MC 1.8.x, otherwise NCP can't use it.

**Comment by asofold** [comment]
Assume resolved by updating.
