### ISSUE TITLE
WorldGuard denied "build flag" issue

### ISSUE THREAD

**Issue by MithrandirCraft** [NoCheatPlus/Issues#67]
Please read the following issue I posted on WorldGuard's issue tracker:

http://dev.enginehub.org/youtrack/issue/WORLDGUARD-3609

I think it may have something to do with NCP. 
Thanks!

Spigot version: 1.8.8
NoCheatPlus version: 3.13.4-BETA-sMD5NET-b901

Edit by staff:
Duplicates: https://github.com/NoCheatPlus/Issues/issues/8

**Comment by Iceee** [comment]
Since the build action is being denied, NoCheatPlus is seeing you attempt to stop in midair.  You are then set back onto the ledge above.  This is normal behavior.

**Comment by MyPictures** [comment]
This is also desired to be like that, because cheaters used it to Nerdpol up in a no-build area and would then end up on top of roofs and what not.
So I dont really see whats the issue in that video.

**Comment by MithrandirCraft** [comment]
I understand the reasoning behind this feature.

But I can use this in order to stop myself from falling in certain situations, it can even be advantageous in pvp if used correctly.

It definetly doesn't look very good.

**Comment by MyPictures** [comment]
But that would be cheating (NoFall damage - avoiding fall damage) because in vanilla Minecraft this wouldn't be possible.

**Comment by MithrandirCraft** [comment]
@MyPictures It can still be usefull for avoiding a fall onto a certain death, like a narrow pit of lava where you can place a block on a wall and roll back, or a hole to the void.

It is true that players will never escape the falldamage, but still, they can escape 100% certain deaths. And the rollback looks really bad.

My suggestion is: Disabling this type of rollbacks if it's going to be a rollback of more than <predefined> blocks.

**Comment by Iceee** [comment]
At the time of the midair slowdown, the player has to be put onto the ground somewhere since correcting trajectory isn't something that's viable.  Taking no action would allow players to fly, so that's not an option either.  Something we've discussed is configurable setback rules, but the problem with setting the player onto the ground directly below them is that they can escape in a similar way.

@asofold perhaps we can adjust the setback location contextually?

**Comment by asofold** [comment]
In any case there'll be new issues with other ways of set-back.

I could imagine context-dependent set-back policies and also global ones.
* Always back to last ground.
* Always down to ground below (trajectory? ~ complicated :p, what if there is no ground below, do we want to enable this variation of fast-fall-by-set-back?).
* Always back to ground if moving up, always down to ground below when moving down.
* Might set-back to last valid end point of a move - however to avoid glide-by set-back, you'd need to penalize repetition somehow .... also might penalize legit players on false positives (teleport by anti cheating plugins always is an issue with latency...) or it might just be useless (if they can just have the 3x in-air set-back, then get set back to ground or wherever).

Not saying it's impossible, i assume we'd add something with 'ground below' next-ish, certainly with configurable policies, in order to give server-owners a choice there.

**Comment by Iceee** [comment]
Taking over and then broadcasting a player's trajectory is a very interesting alternative to a single position setback.  It wouldn't be a great experience visually for the player being setback, but it would certainly prevent other players from seeing weird teleports.

**Comment by asofold** [comment]
@Iceee 

It might be more nice to watch, but given the complexity, it may be prone to creating new trouble as well, thinking of stuff happening before trajectory has been played out fully, so we'd be in need of being able to change processing based on both Bukkit events and outgoing packet events. 

Perhaps just setting to ground will also be rendered much like falling, even if it looks like too fast falling. Should try that first :p.

**Comment by MithrandirCraft** [comment]
What's wrong with my suggestion? Just make a config option for allowing rollback as long as the player isn't going to get rolled back more than a certain preconfigured ammount of blocks.

This wouldn't sound abusable, I can't imagine what could be abused as long as the block still dissapears. The player may have a fraction of a second to stand on it (And may cause falldamage?), but it won't be abusable on this type of situations where the player jumps from high places and gets rolled back like 40 blocks, in these cases, the rollback shouldn't occur.

**Comment by asofold** [comment]
@MithrandirCraft 

In fact having distance-based limits to supposed ground below or to the set-back, would also be a way to make things more configurable.

Not setting back at all is a peculiar thing to do, because it allows cheats even for vanilla players with other setups, thinking of a very high wall, placing a block client side against the wall, in order to continue falling with 0-speed after set-back, e.g. to reach a cave. Apart from that (other) special case, you always have to think of cheat clients abusing these features, so i am not sure if "not setting back" is such a good option. Cheaters also would have a lot of time with freecam and blink and other inspection/replay methods, even without specialized cheats.

On the other hand, all these methods have certain advantages and disadvantages, which may or may not suit server owners, so if we can nail down the 'not actually set-back' thing to 'not quite abusable and optional anyway' it'd be an option. Actually i have already thought about that possibility, sending the player the set-back to last legit move endpoint, potentially in-air, and also sending them a velocity to continue moving, however that is going to need a couple of alterations internally (bind velocity to a set-back to avoid removing it due to latency, detect not using the velocity, possibly calculate what part of velocity is usable).

All in all i think setting back to ground isn't that far off for your case, possibly with settings for distinction with distances to ground and to set-back. Not sure i understand right, though.

**Comment by MithrandirCraft** [comment]
I see the issue with what I suggested yeah... and you did understand my suggestion.

**Comment by asofold** [comment]
Effectively this should be a special case (duplicate) of the ticket https://github.com/NoCheatPlus/Issues/issues/8 . Correct me if i'm wrong.

**Comment by MithrandirCraft** [comment]
Yes, and now that I see that ticket, I realize it's been a very old time issue on parkour :P

**Comment by MithrandirCraft** [comment]
Allthough that issue doesn't seem to mention anything about WorldGuard.
@MyPictures opened it, he should know :P

**Comment by asofold** [comment]
@MithrandirCraft It doesn't mention WorldGuard in particular, but the set-back stuff is in there.

**Comment by MyPictures** [comment]
@MithrandirCraft The issue that is tackled on that other ticket would also solve the issue you are having in here if I am not mistaken.

**Comment by MithrandirCraft** [comment]
yyyes... there is no workaround on this on my side right?

I think my issue would be fixed if that other ticket was solved. It seems to be the same, but with different examples and perspective.

**Comment by asofold** [comment]
@MithrandirCraft It mentions 'placing blocks where you can't build', though there might be a 'no' too much somewhere, not sure right now.  It's not forgotten...
