### ISSUE TITLE
Kicked for flying (or related) too strict. 

### ISSUE THREAD

**Issue by Done84** [NoCheatPlus/Issues#80]
Hello. Since i updated to a more recent version players keep getting kicked for:
"Kicked for flying (or related)"
Usually by failing survival fly checks for very small values, under a block usually. I am not sure if this is a bug or if i just need to make the check less strict.

Example:
[00:53:47] [Craft Scheduler Thread - 3190/INFO]: [NoCheatPlus] ZuckerGamesYT failed SurvivalFly: tried to move from -693.03, 31.32, 825.30 to -692.98, 31.40, 825.31 over a distance of 0.09 block(s). VL 1067.
[00:53:47] [Craft Scheduler Thread - 3190/INFO]: [NoCheatPlus] ZuckerGamesYT failed SurvivalFly: tried to move from -693.05, 31.11, 825.30 to -692.98, 31.40, 825.31 over a distance of 0.30 block(s). VL 2107.
[00:53:47] [Server thread/INFO]: [PvPManager] ZuckerGamesYT tried to escape combat and got punished!
[00:53:47] [Server thread/INFO]: §cZuckerGamesYT was slain by Axel_Awesome using [§8-§2Member9 Sword§8-]
[00:53:47] [Server thread/INFO]: ZuckerGamesYT left the game.
[00:53:47] [Server thread/WARN]: handleDisconnection() called twice
[00:53:47] [Craft Scheduler Thread - 3190/INFO]: [NoCheatPlus] (CONSOLE) Kicked ZuckerGamesYT : Kicked for flying (or related)

I am using build #904 on spigot 1.8.8.

Config: http://pastebin.com/s8Gj1UA6

**Comment by asofold** [comment]
@Done84 This is not 'spigot' like 'PaperSpigot'? We do prefer to have the output of '/ncp version', also to know if there are special hooks or if ProtocolLib is used :).

The log is somewhat odd, due to a dead player getting kicked for flying? Can't be 100% sure, as there are plugins changing damage, preventing death, teleporting players, etc. (Fail survivalfly -> Tried to escape combat and got punished (how?) -> slain -> left the game -> disconnected -> kicked for flying) Are there combat logging plugins in use?

**Comment by Done84** [comment]
Its regular spigot.

I am using PvPmanager to avoid combat log, I've used it for years along side NCP. After NCP kicks the players for "fly" PvPmanager detects it as combat log (when the player is in fact in pvp). But this also happens without players being in Combat Tag. It also happens with the 'passable check' where players often get stuck into blocks wile mining and time out.

> This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)


> INFO Hooks: AllViolations(NCP) 1.0 | mcMMO(cncp) 2.3
> INFO packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance
> INFO defaults: pvpKnockBackVelocity
> INFO checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
> INFO blocks: BlocksMC1_4(base) | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
> INFO Features:
> INFO MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
> INFO Plugin: 3.13.5-SNAPSHOT-sMD5NET-b904
> INFO #### NoCheatPlus ####
> INFO (detected: 1.8.8)
> INFO git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
> INFO #### Server ####
> INFO ---- Version information -

**Comment by asofold** [comment]
Build 901 is already slightly outdated, though there has been another bigger change towards build 914 (or even 920).

**Comment by Done84** [comment]
I will update and report back. One question thought, i remember many versions ago i would get a console warning about having to regen my config, now it looks like that feature is gone. How do i know when i should regen it to default then re-edit all my custom commands, messages etc?

**Comment by asofold** [comment]
@Done84 NCP will bully server owners with the configuraiton, if we overwrite an existing configuration value, or if we remove values that might be of relevance.

If NCP hasn't complained since, we have not changed the config in such ways, or we forgot to set the 'last change' build. This is very coarse, it doesn't check if you have values set differently than in the default configuration, it just checks the build that you generated your configuration with (configversion section).

To get an estimate if/what we might've changed you could refer to the build-infos page: https://github.com/NoCheatPlus/Docs/wiki/Build-Infos

There we might advertise config changes, e.g. like with build 699: https://github.com/NoCheatPlus/Docs/wiki/Build-Infos#31012-snapshot-smd5net-b699cumulative

**Comment by Done84** [comment]
I'm now on build 922 and i still have the same issue.
http://prnt.sc/a8tca5

**Comment by asofold** [comment]
So they trigger survivalfly standing on an enderchest 'just having teleported there' ?

**Comment by Done84** [comment]
@asofold Yes. It triggers if they teleport, if they are just standing around on them it triggers but only on occasion, but that's not my concern the real problem are the constant passable false positives for distances such a 0.10 blocks, it happens way to often, im not sure but it might be related to players who suffer from more Lag. Survival fly also trigger a lot.

I recorded 2 mins of me teleporting to each player that gets a positive, maybe it can help.
https://www.youtube.com/watch?v=xAc8Af1TZyg&feature=youtu.be

**Comment by asofold** [comment]
Passable violations with 0.1 distance (downwards) are bound to happen with Minecraft design-wise. Players just send 'slow falling' moves during rendering and  NCP has to prevent the moving.

The non-full blocks / teleporting is still related to the kicking? Perhaps that should be an extra issue, if not.

**Comment by Done84** [comment]
@asofold Oh ok, then i should close this.

Is there a way i can only be notified in chat if the value is high enough for it to actually be someone trying to use phase hacks or similar? Cause the spam is annoying and keeps us from paying attention to real hacks.
`      actions: cancel vl>10 log:passable:0:5:if cancel vl>50 log:passable:0:5:icf cancel`

**Comment by asofold** [comment]
Yes, there are ways to alter the actions. For one thing you can remove the 'i' from the suffix of 'log:passable:0:5:if' to not have those violations in ingame chat. Second you can increase the violation level for which things are logged by altering vl>10 and vl>50 to higher values.

A player who has 10 seconds delay on rendering, might create 200 passable violations (...) for a maximal estimation. This would be extreme, but 80 or so is easily observable with slower rendering clients.

Honestly, one can't really distinguish a very slow rendering client from phase with the current check. In future we should add something to know if passable happens near login location or after the player started some action or not, we might also distinguish if the envelope can be 'slow falling' or hclip/vclip. The thing is, that an actual cheater might just re-log in order to try to vclip somewhere, so they'll then stay under the radar same way. Not saying we can't do anything, it just doesn't get to high priority right now.
