### ISSUE TITLE
Slab, chest, enderchest, enchant table freeze bug

### ISSUE THREAD

**Issue by maxlehot1234** [NoCheatPlus/Issues#96]
Hi everyone, I just want to know if anyone have a problem with slab, enderchest, chest and enchant table?
If I walk on them or go on top of them, I simply freeze and can't move...
I need to use a command to tp me at any place (spawn, warp, etc)

Directly when I uninstall nocheatplus, all works great.
I have the latest nocheatplus devbuild and latest spigot 1.9 version.

Thank you so much and have a nice day/night

**Comment by Sprungente** [comment]
i'm sure he will fix the bug, but he is at the moment sick. It might take a little longer.

**Comment by asofold** [comment]
Please always add the output of the 'ncp version' command, for quick updating on 1.9 the build number of NCP might suffice for starters, but we'll soon need that one to distinguish from where reports come in. Build 933 adds native block shape access. It's marked [BLEEDING] due to not being able to test all to much.

Please keep checking for development builds for 1.9, as it's very early after the release.

**Comment by Platinteufel** [comment]
Seems fixed in 933, thank you :)

**Comment by asofold** [comment]
Please keep checking for updates for both of SPigot and NCP :).
